`${API_BASE_URL}/adhesives/get`
`${API_BASE_URL}/brush/get`
`${API_BASE_URL}/cements/get`
`${API_BASE_URL}/cleaning/get`
`${API_BASE_URL}/dry/get`
`${API_BASE_URL}/electrical/adaptors/get`
`${API_BASE_URL}/electrical/ceilingRoses/get`
`${API_BASE_URL}/electrical/dimmer/get`
`${API_BASE_URL}/electrical/distributionBoards/get`
`${API_BASE_URL}/electrical/doorBells/get`
`${API_BASE_URL}/electrical/dPswitch/get`
`${API_BASE_URL}/electrical/earthingAccessories/get`
`${API_BASE_URL}/electrical/eLCBsRCCBs/get`
`${API_BASE_URL}/electrical/flexibleConduit/get`
`${API_BASE_URL}/electrical/flexibleWires/get`
`${API_BASE_URL}/electrical/fuseCarriers/get`
`${API_BASE_URL}/electrical/holders/get`
`${API_BASE_URL}/electrical/indicator/get`
`${API_BASE_URL}/electrical/insulationTapes/get`
`${API_BASE_URL}/electrical/isolators/get`
`${API_BASE_URL}/electrical/jacks/get`
`${API_BASE_URL}/electrical/kITKATFuses/get`
`${API_BASE_URL}/electrical/mainSwitch/get`
`${API_BASE_URL}/electrical/mCB/get`
`${API_BASE_URL}/electrical/modularSurfaceBox/get`
`${API_BASE_URL}/electrical/motors/get`
`${API_BASE_URL}/electrical/motorStarters/get`
`${API_BASE_URL}/electrical/others/get`
`${API_BASE_URL}/electrical/pinTop/get`
`${API_BASE_URL}/electrical/plug/get`
`${API_BASE_URL}/electrical/powerStrips/get`
`${API_BASE_URL}/electrical/pvCClips/get`
`${API_BASE_URL}/electrical/regulators/get`
`${API_BASE_URL}/electrical/rotarySwitch/get`
`${API_BASE_URL}/electrical/sockets/get`
`${API_BASE_URL}/electrical/switchAndSocket/get`
`${API_BASE_URL}/electrical/switches/get`
`${API_BASE_URL}/electrical/switchPlates/get`
`${API_BASE_URL}/electrical/travelAdaptor/get`
`${API_BASE_URL}/electrical/tVOutlets/get`
`${API_BASE_URL}/electrical/uniSwitch/get`
`${API_BASE_URL}/electrical/waterHeater/get`
`${API_BASE_URL}/electrical/wiresAndCables/get`
`${API_BASE_URL}/electrical/accessories/get`
`${API_BASE_URL}/electrical/circulardeepbox/get`
`${API_BASE_URL}/electrical/circularsurfacebox/get`
`${API_BASE_URL}/electrical/rigidtype/get`
`${API_BASE_URL}/electrical/cabinfans/get`
`${API_BASE_URL}/electrical/ceilingfans/get`
`${API_BASE_URL}/electrical/pedestalfans/get`
`${API_BASE_URL}/electrical/tablefans/get`
`${API_BASE_URL}/electrical/ventilationexhaustfans/get`
`${API_BASE_URL}/electrical/wallmountingfans/get`
`${API_BASE_URL}/electrical/ceilinglight/get`
`${API_BASE_URL}/electrical/cfl/get`
`${API_BASE_URL}/electrical/desklight/get`
`${API_BASE_URL}/electrical/focuslight/get`
`${API_BASE_URL}/electrical/gardenlight/get`
`${API_BASE_URL}/electrical/gatelight/get`
`${API_BASE_URL}/electrical/gls/get`
`${API_BASE_URL}/electrical/home/get`
`${API_BASE_URL}/electrical/lamps/get`
`${API_BASE_URL}/electrical/ledbatten/get`
`${API_BASE_URL}/electrical/ledbulbs/get`
`${API_BASE_URL}/electrical/leddownlightersspotlight/get`
`${API_BASE_URL}/electrical/ledluminaires/get`
`${API_BASE_URL}/electrical/ledpanellight/get`
`${API_BASE_URL}/electrical/ledspotlight/get`
`${API_BASE_URL}/electrical/ledstreetlight/get`
`${API_BASE_URL}/electrical/ledstrips/get`
`${API_BASE_URL}/electrical/ledsurfacelight/get`
`${API_BASE_URL}/electrical/lightelectronics/get`
`${API_BASE_URL}/electrical/mirrorlight/get`
`${API_BASE_URL}/electrical/reflections/get`
`${API_BASE_URL}/electrical/standardincandescent/get`
`${API_BASE_URL}/electrical/tbulb/get`
`${API_BASE_URL}/electrical/tubelight/get`
`${API_BASE_URL}/electrical/underwaterlights/get`
`${API_BASE_URL}/electrical/walllight/get`
`${API_BASE_URL}/fiber/get`
`${API_BASE_URL}/fitting/get`
`${API_BASE_URL}/hardware/get`
`${API_BASE_URL}/home/get`
`${API_BASE_URL}/homedecor/get`
`${API_BASE_URL}/locks/patch-fittings/get`
`${API_BASE_URL}/locks/mortise-lock-body/get`
`${API_BASE_URL}/locks/mortice-locks/get`
`${API_BASE_URL}/locks/door-accessories/concealed-hinges/get`
`${API_BASE_URL}/locks/door-accessories/door-eye/get`
`${API_BASE_URL}/locks/door-accessories/door-stopper/get`
`${API_BASE_URL}/locks/door-accessories/hinges/get`
`${API_BASE_URL}/locks/door-accessories/magnetic-door-stoppers/get`
`${API_BASE_URL}/locks/door-accessories/wooden-sliding-door-fittings/get`
`${API_BASE_URL}/locks/door-accessories/ball-bearing-door-hinges/get`
`${API_BASE_URL}/locks/door-controls/door-closer/get`
`${API_BASE_URL}/locks/door-controls/door-stopper/get`
`${API_BASE_URL}/locks/door-controls/hydraulic-door-closers/get`
`${API_BASE_URL}/locks/door-handles/door-kings/get`
`${API_BASE_URL}/locks/door-handles/door-pulls/get`
`${API_BASE_URL}/locks/door-locks/dimple-key/get`
`${API_BASE_URL}/locks/door-locks/diamant-padlocks/get`
`${API_BASE_URL}/locks/door-locks/dead-locks/get`
`${API_BASE_URL}/locks/door-locks/cylindrical-locks/get`
`${API_BASE_URL}/locks/door-locks/cupboard-locks/get`
`${API_BASE_URL}/locks/door-locks/centre-shutter-locks/get`
`${API_BASE_URL}/locks/door-locks/tri-bolt-locks/get`
`${API_BASE_URL}/locks/door-locks/smart-key/get`
`${API_BASE_URL}/locks/door-locks/side-lock'/get`
`${API_BASE_URL}/locks/door-locks/rim-dead-lock/get`
`${API_BASE_URL}/locks/door-locks/pull-handles-for-main-doors/get`
`${API_BASE_URL}/locks/door-locks/night-latch/get`
`${API_BASE_URL}/locks/door-locks/main-door-lock/get`
`${API_BASE_URL}/locks/door-locks/knob-locks/get`
`${API_BASE_URL}/locks/door-locks/jemmy-proof-door-lock/get`
`${API_BASE_URL}/locks/door-locks/drawer-lock/get`
`${API_BASE_URL}/locks/door-locks/disc-pad-locks/get`
`${API_BASE_URL}/locks/folding-brackets/thick-door-hinge/get`
`${API_BASE_URL}/locks/folding-brackets/soft-close-drawer-channel/get`
`${API_BASE_URL}/locks/folding-brackets/slip-on-hinge/get`
`${API_BASE_URL}/locks/folding-brackets/heavy-duty-drawer-slides/get`
`${API_BASE_URL}/locks/folding-brackets/folding-brackets/get`
`${API_BASE_URL}/locks/folding-brackets/drawer-channels/get`
`${API_BASE_URL}/locks/folding-brackets/clip-on-soft-hinge/get`
`${API_BASE_URL}/locks/folding-brackets/clip-on-soft-hinge-4-hole/get`
`${API_BASE_URL}/locks/folding-brackets/cabinet-hinge/get`
`${API_BASE_URL}/locks/folding-brackets/blind-corner-hinge/get`
`${API_BASE_URL}/locks/furniture-fittings/nuvo/get`
`${API_BASE_URL}/locks/furniture-fittings/multi-purpose-lock/get`
`${API_BASE_URL}/locks/furniture-fittings/furniture-fittings/get`
`${API_BASE_URL}/locks/furniture-fittings/drawer-locks/get`
`${API_BASE_URL}/locks/furniture-fittings/drawer-cupboard-lock/get`
`${API_BASE_URL}/locks/furniture-fittings/curvo/get`
`${API_BASE_URL}/locks/furniture-fittings/supernova/get`
`${API_BASE_URL}/locks/furniture-fittings/table-lock/get`
`${API_BASE_URL}/locks/glass-hardware/sliding-system/get`
`${API_BASE_URL}/locks/glass-hardware/shower-cubicle-hinge/get`
`${API_BASE_URL}/locks/glass-hardware/glass-hardware/get`
`${API_BASE_URL}/locks/glass-hardware/glass-door-pull-handle/get`
`${API_BASE_URL}/locks/glass-hardware/glass-door-lock/get`
`${API_BASE_URL}/locks/glass-hardware/glass-door-fitting/get`
`${API_BASE_URL}/locks/glass-hardware/floor-spring/get`
`${API_BASE_URL}/locks/glass-hardware/floor-spring-combo-set/get`
`${API_BASE_URL}/locks/lever-mortise-locks/lever-mortise-locks/get`
`${API_BASE_URL}/locks/lever-mortise-locks/exshi-security-cylinders/get`
`${API_BASE_URL}/locks/lever-mortise-locks/europrofile-mortise-pin-cylinder-with-master-key/get`
`${API_BASE_URL}/locks/lever-mortise-locks/europrofile-mortise-pin-cylinder/get`
`${API_BASE_URL}/locks/lever-mortise-locks/europrofile-mortise-lock-bodies/get`
`${API_BASE_URL}/locks/lever-mortise-locks/combipack-with-6-lever-mortise-lock/get`
`${API_BASE_URL}/locks/padlocks/ultra-shutter-locks/get`
`${API_BASE_URL}/locks/padlocks/square-type-padlock/get`
`${API_BASE_URL}/locks/padlocks/round-type-padlock/get`
`${API_BASE_URL}/locks/padlocks/premium-padlocks/get`
`${API_BASE_URL}/locks/padlocks/padlocks/get`
`${API_BASE_URL}/locks/padlocks/disc-padlocks/get`
`${API_BASE_URL}/locks/popular-mortise-series/victoria/get`
`${API_BASE_URL}/locks/popular-mortise-series/towy-low-height-design/get`
`${API_BASE_URL}/locks/popular-mortise-series/ssd-type-tube-lever/get`
`${API_BASE_URL}/locks/popular-mortise-series/pull-handles/get`
`${API_BASE_URL}/locks/popular-mortise-series/popular-mortise-series/get`
`${API_BASE_URL}/locks/popular-mortise-series/oliver/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh16/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh15-low-height-design/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh14/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh13/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh12/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh06/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh11/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh10/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh09/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh08/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh07/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh05/get`
`${API_BASE_URL}/locks/popular-mortise-series/neh04/get`
`${API_BASE_URL}/locks/popular-mortise-series/matiz/get`
`${API_BASE_URL}/locks/popular-mortise-series/main-door-set/get`
`${API_BASE_URL}/locks/popular-mortise-series/gloria/get`
`${API_BASE_URL}/locks/popular-mortise-series/cylindrical-locks/get`
`${API_BASE_URL}/locks/popular-mortise-series/corner-fetch-series/get`
`${API_BASE_URL}/locks/popular-mortise-series/combi-set/get`
`${API_BASE_URL}/locks/popular-mortise-series/classic-lock/get`
`${API_BASE_URL}/locks/popular-mortise-series/bm06/get`
`${API_BASE_URL}/locks/popular-mortise-series/bm04/get`
`${API_BASE_URL}/locks/popular-mortise-series/bm02/get`
`${API_BASE_URL}/locks/popular-mortise-series/bm01/get`
`${API_BASE_URL}/locks/premium-mortise-series/seh-series/get`
`${API_BASE_URL}/locks/premium-mortise-series/premium-mortise-series/get`
`${API_BASE_URL}/locks/premium-mortise-series/phoenix/get`
`${API_BASE_URL}/locks/premium-mortise-series/orbit/get`
`${API_BASE_URL}/locks/premium-mortise-series/mercury/get`
`${API_BASE_URL}/locks/premium-mortise-series/evva3ks-regalis-mortise/get`
`${API_BASE_URL}/locks/premium-mortise-series/europrofile-brass-handle-set-240mm/get`
`${API_BASE_URL}/locks/premium-mortise-series/combipack-with-240mm-euro-mortise-lock/get`
`${API_BASE_URL}/locks/premium-mortise-series/allure-rossette-series/get`
`${API_BASE_URL}/locks/rim-locks/ultra-xl-vertibolt/get`
`${API_BASE_URL}/locks/rim-locks/ultra-xl-twinbolt/get`
`${API_BASE_URL}/locks/rim-locks/ultra-xl-tribolt/get`
`${API_BASE_URL}/locks/rim-locks/ultra-xl-rim-deadbolt/get`
`${API_BASE_URL}/locks/rim-locks/ultra-vertibolt/get`
`${API_BASE_URL}/locks/rim-locks/ultra-tribolt/get`
`${API_BASE_URL}/locks/rim-locks/ultra-retrofit-adaptor/get`
`${API_BASE_URL}/locks/rim-locks/ultra-latchbolt-carton/get`
`${API_BASE_URL}/locks/rim-locks/rim-locks/get`
`${API_BASE_URL}/locks/rim-locks/pin-cylinder-rim-locks/get`
`${API_BASE_URL}/locks/rim-locks/pentabolt-aries/get`
`${API_BASE_URL}/locks/rim-locks/night-latch-7-lever/get`
`${API_BASE_URL}/locks/rim-locks/exs-astro/get`
`${API_BASE_URL}/locks/rim-locks/exs-altrix/get`
`${API_BASE_URL}/paint/acrylic-emulsion-paint/get`
`${API_BASE_URL}/paint/adhesive-thinner-adhesive/get`
`${API_BASE_URL}/paint/adhesive-thinner-thinner/get`
`${API_BASE_URL}/paint/aspa-paints/get`
`${API_BASE_URL}/paint/automative-paints-aspa-paints/get`
`${API_BASE_URL}/paint/brushes-rollers-paint-brushes/get`
`${API_BASE_URL}/paint/brushes-rollers-rollers/get`
`${API_BASE_URL}/paint/brushes-rollers-spray-paints/get`
`${API_BASE_URL}/paint/distemper-acrylic-distemper/get`
`${API_BASE_URL}/paint/distemper-synthetic-distemper/get`
`${API_BASE_URL}/paint/emulsion-exterior-emulsion/get`
`${API_BASE_URL}/paint/emulsion-interior-emulsion/get`
`${API_BASE_URL}/paint/emulsion-tile-guard/get`
`${API_BASE_URL}/paint/emulsion-wall-texture/get`
`${API_BASE_URL}/paint/enamel-gloss-enamel/get`
`${API_BASE_URL}/paint/enamel-satin-enamel/get`
`${API_BASE_URL}/paint/enamel-synthetic-enamel/get`
`${API_BASE_URL}/paint/exterior-paints/get`
`${API_BASE_URL}/paint/floor-paints/get`
`${API_BASE_URL}/paint/industrial-coatings/get`
`${API_BASE_URL}/paint/interior-paints/get`
`${API_BASE_URL}/paint/painting-accessories-painting-tools/get`
`${API_BASE_URL}/paint/painting-accessories-sandpaper-rolls/get`
`${API_BASE_URL}/paint/painting-accessories-stencils/get`
`${API_BASE_URL}/paint/painting-tools/get`
`${API_BASE_URL}/paint/primer-acrylic-primer/get`
`${API_BASE_URL}/paint/primer-cement-primer/get`
`${API_BASE_URL}/paint/primer-exterior-primer/get`
`${API_BASE_URL}/paint/primer-interior-primer/get`
`${API_BASE_URL}/paint/primer-metal-primer/get`
`${API_BASE_URL}/paint/primer-solvent-primer/get`
`${API_BASE_URL}/paint/primer-wood-primer/get`
`${API_BASE_URL}/paint/primer-and-wall-putty/get`
`${API_BASE_URL}/paint/sanitizer/get`
`${API_BASE_URL}/paint/spray-paints/get`
`${API_BASE_URL}/paint/stainers-universal-stainers/get`
`${API_BASE_URL}/paint/stainers-wood-stainers/get`
`${API_BASE_URL}/paint/stainers-thinners/get`
`${API_BASE_URL}/paint/stencils/get`
`${API_BASE_URL}/paint/tile-guard/get`
`${API_BASE_URL}/paint/top-brands-dulex-paints/get`
`${API_BASE_URL}/paint/top-brands-asian-paints/get`
`${API_BASE_URL}/paint/top-brands-neroloc-paints/get`
`${API_BASE_URL}/paint/top-brands-jk-wall-putty/get`
`${API_BASE_URL}/paint/wall-putty-acrylic-wall-putty/get`
`${API_BASE_URL}/paint/wall-putty-kpf-wall-putty/get`
`${API_BASE_URL}/paint/wall-putty-powder-wall-putty/get`
`${API_BASE_URL}/paint/wall-stickers-wallpapers/get`
`${API_BASE_URL}/paint/waterproofing-crack-fillers/get`
`${API_BASE_URL}/paint/waterproofing-waterproof-basecoat/get`
`${API_BASE_URL}/paint/wood-finishes-glass-coatings/get`
`${API_BASE_URL}/paint/wood-finishes-melamyne/get`
`${API_BASE_URL}/paint/wood-finishes-nc/get`
`${API_BASE_URL}/paint/wood-finishes-polish/get`
`${API_BASE_URL}/paint/wood-finishes-pu/get`
`${API_BASE_URL}/paint/wood-finishes-sealer/get`
`${API_BASE_URL}/paint/wood-finishes-varnish-black-board-paint/get`
`${API_BASE_URL}/paint/wood-finishes-wood-putty/get`
`${API_BASE_URL}/paint/wood-metal/get`
`${API_BASE_URL}/pipe/finolex-pipes/get`
`${API_BASE_URL}/pipe/ashirvad-pipes/get`
`${API_BASE_URL}/pipe/astral-pipes/get`
`${API_BASE_URL}/pipe/nepul-pipes/get`
`${API_BASE_URL}/pipe/birla-pipes/get`
`${API_BASE_URL}/pipe/prince-pipes/get`
`${API_BASE_URL}/pipe/prakash-pipes/get`
`${API_BASE_URL}/pipe/supreme-pipes/get`
`${API_BASE_URL}/pipe/tata-pipes/get`
`${API_BASE_URL}/pipe/tsa-pipes/get`
`${API_BASE_URL}/pvcmats/door/get`
`${API_BASE_URL}/pvcmats/floor/get`
`${API_BASE_URL}/roofer/metal/get`
`${API_BASE_URL}/roofer/shingles/get`
`${API_BASE_URL}/sanitary/acrylic-products/get`
`${API_BASE_URL}/sanitary/bathroom-accessories/get`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-altius/get`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-bathsense-essentials/get`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-bathsense-showers/get`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-colossus/get`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-invictus/get`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-maximus/get`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-spry/get`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-theta/get`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-essentials/get`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-pedestals/get`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-venus/get`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-washbasins/get`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-water-closet/get`
`${API_BASE_URL}/sanitary/closets/get`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-eurosmart-series/get`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-flowmore-series/get`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-new-super-glow-series/get`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-royale-series/get`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-treemo-series/get`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-xrossa-series/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-almond/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-arrow/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-bold/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-budget/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-concept/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-deluxe/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-eeco/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-expert/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-florence/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-glass-bowl-faucet/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-idea/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-jazz/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-ket/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-milano/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-nano/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-nexa/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-niagra/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-nice/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-omega/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-passion/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-royal/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-slimline/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-splash/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-square-f/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-square-s/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-super/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-tri/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-acrylic-accessories/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-almond/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-anglo/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-budget/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-dolphin/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-ecco/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-keti/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-qubix/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-square/get`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-supreme/get`
`${API_BASE_URL}/sanitary/corsa-flushing-cistern/get`
`${API_BASE_URL}/sanitary/corsa-kitchen-kitchen-faucets/get`
`${API_BASE_URL}/sanitary/corsa-kitchen-kitchen-sink/get`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-ball-valves/get`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-mini-angle-cock/get`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-mouth-operated/get`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-pressmatic-push-cock/get`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-sensor-taps/get`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-soap-dispenser/get`
`${API_BASE_URL}/sanitary/corsa-showers-health-faucet/get`
`${API_BASE_URL}/sanitary/corsa-shower-soverhead-shower/get`
`${API_BASE_URL}/sanitary/corsa-showers-rain-shower/get`
`${API_BASE_URL}/sanitary/corsa-showers-telephonic-shower/get`
`${API_BASE_URL}/sanitary/essess-accessories-series1-croma/get`
`${API_BASE_URL}/sanitary/essess-accessories-series2-swing/get`
`${API_BASE_URL}/sanitary/essess-accessories-series3-tarim/get`
`${API_BASE_URL}/sanitary/essess-accessories-series5-hotelier-series/get`
`${API_BASE_URL}/sanitary/essess-accessories-series6-cruzo/get`
`${API_BASE_URL}/sanitary/essess-accessories-series7-deon/get`
`${API_BASE_URL}/sanitary/essess-accessories-series8-series/get`
`${API_BASE_URL}/sanitary/essess-auto-close-taps/get`
`${API_BASE_URL}/sanitary/essess-celato/get`
`${API_BASE_URL}/sanitary/essess-croma/get`
`${API_BASE_URL}/sanitary/essess-cruzo/get`
`${API_BASE_URL}/sanitary/essess-deon/get`
`${API_BASE_URL}/sanitary/essess-series/get`
`${API_BASE_URL}/sanitary/essess-echo/get`
`${API_BASE_URL}/sanitary/essess-essentials/get`
`${API_BASE_URL}/sanitary/essess-hotelier-series/get`
`${API_BASE_URL}/sanitary/essess-s03/get`
`${API_BASE_URL}/sanitary/essess-lab-taps/get`
`${API_BASE_URL}/sanitary/essess-new-dune/get`
`${API_BASE_URL}/sanitary/essess-new-xess/get`
`${API_BASE_URL}/sanitary/essess-quadra/get`
`${API_BASE_URL}/sanitary/essess-sensors/get`
`${API_BASE_URL}/sanitary/essess-showers-hand-showers/get`
`${API_BASE_URL}/sanitary/essess-showers-overhead-showers/get`
`${API_BASE_URL}/sanitary/essess-showers-rainfall-showers/get`
`${API_BASE_URL}/sanitary/essess-showers-shower-arms/get`
`${API_BASE_URL}/sanitary/essess-tarim/get`
`${API_BASE_URL}/sanitary/essess-trand/get`
`${API_BASE_URL}/sanitary/faucets/get`
`${API_BASE_URL}/sanitary/hardware-bathroom-accessories/get`
`${API_BASE_URL}/sanitary/health-faucet/get`
`${API_BASE_URL}/sanitary/hindware-add-on/get`
`${API_BASE_URL}/sanitary/hindware-bath-tub/get`
`${API_BASE_URL}/sanitary/hindware-cisterns/get`
`${API_BASE_URL}/sanitary/hindware-faucets-angular-stop-cock/get`
`${API_BASE_URL}/sanitary/hindware-faucets-bath-spout/get`
`${API_BASE_URL}/sanitary/hindware-faucets-bib-cock/get`
`${API_BASE_URL}/sanitary/hindware-faucets-chbm/get`
`${API_BASE_URL}/sanitary/hindware-faucets-concealed-stop-cock/get`
`${API_BASE_URL}/sanitary/hindware-faucets-csc-exp-kit/get`
`${API_BASE_URL}/sanitary/hindware-faucets-deusch-mixer/get`
`${API_BASE_URL}/sanitary/hindware-faucets-exposed-mixers/get`
`${API_BASE_URL}/sanitary/hindware-faucets-flush-cock/get`
`${API_BASE_URL}/sanitary/hindware-faucets-medical-series/get`
`${API_BASE_URL}/sanitary/hindware-faucets-mixer-faucet/get`
`${API_BASE_URL}/sanitary/hindware-faucets-pillar-cock/get`
`${API_BASE_URL}/sanitary/hindware-faucets-pillar-cock-tall/get`
`${API_BASE_URL}/sanitary/hindware-faucets-pillar-faucet/get`
`${API_BASE_URL}/sanitary/hindware-faucets-pressmatic/get`
`${API_BASE_URL}/sanitary/hindware-faucets-recessed/get`
`${API_BASE_URL}/sanitary/hindware-faucets-single-lever-divertor/get`
`${API_BASE_URL}/sanitary/hindware-faucets-sink-cock/get`
`${API_BASE_URL}/sanitary/hindware-faucets-sink-mixer/get`
`${API_BASE_URL}/sanitary/hindware-faucets-slbm-faucet/get`
`${API_BASE_URL}/sanitary/hindware-faucets-slbm-faucet-tall/get`
`${API_BASE_URL}/sanitary/hindware-showers-rain-showers/get`
`${API_BASE_URL}/sanitary/hindware-wash-basins/get`
`${API_BASE_URL}/sanitary/hindware-water-closets/get`
`${API_BASE_URL}/sanitary/jaquar/get`
`${API_BASE_URL}/sanitary/kitchen-sinks/get`
`${API_BASE_URL}/sanitary/leo-bath-fittings-bathroom-accessories-bathroom-accessories/get`
`${API_BASE_URL}/sanitary/leo-bath-fittings-faucets/get`
`${API_BASE_URL}/sanitary/leo-bath-fittings-valve/get`
`${API_BASE_URL}/sanitary/pamay-faucets-faucets/get`
`${API_BASE_URL}/sanitary/pamay-showers-showers/get`
`${API_BASE_URL}/sanitary/parryware-accessories-accessories/get`
`${API_BASE_URL}/sanitary/parryware-angle-valves-angle-valves/get`
`${API_BASE_URL}/sanitary/parryware-below-counter-basins-below-counter-basins/get`
`${API_BASE_URL}/sanitary/parryware-bowl-basins-bowl-basins/get`
`${API_BASE_URL}/sanitary/parryware-closets-closets/get`
`${API_BASE_URL}/sanitary/parryware-concealed-cistern-concealed-cistern/get`
`${API_BASE_URL}/sanitary/parryware-european-water-closet-european-water-closet/get`
`${API_BASE_URL}/sanitary/parryware-faucets-flush-cocks/get`
`${API_BASE_URL}/sanitary/parryware-faucets-flush-valve/get`
`${API_BASE_URL}/sanitary/parryware-faucets-health-faucets/get`
`${API_BASE_URL}/sanitary/parryware-faucets-kitchen-sinks/get`
`${API_BASE_URL}/sanitary/parryware-faucets-pedestals/get`
`${API_BASE_URL}/sanitary/parryware-polymer-cisterns-polymer-cisterns/get`
`${API_BASE_URL}/sanitary/parryware-push-plates-push-plates/get`
`${API_BASE_URL}/sanitary/parryware-seat-covers-seat-covers/get`
`${API_BASE_URL}/sanitary/parryware-semi-recessed-basins-semi-recessed-basins/get`
`${API_BASE_URL}/sanitary/parryware-shower-enclosures-shower-enclosures/get`
`${API_BASE_URL}/sanitary/parryware-shower-panels-shower-panels/get`
`${API_BASE_URL}/sanitary/parryware-showers-showers/get`
`${API_BASE_URL}/sanitary/parryware-utsav-range-utsav-range/get`
`${API_BASE_URL}/sanitary/parryware-wash-basins-wash-basins/get`
`${API_BASE_URL}/sanitary/parryware-waste-coupling-waste-coupling/get`
`${API_BASE_URL}/sanitary/parryware-water-heaters-water-heaters/get`
`${API_BASE_URL}/sanitary/pearl-precious-products-edge-edge/get`
`${API_BASE_URL}/sanitary/showers/get`
`${API_BASE_URL}/sanitary/taps/get`
`${API_BASE_URL}/sanitary/washbasins/get`
`${API_BASE_URL}/sanitary/waterman-accessories/get`
`${API_BASE_URL}/sanitary/waterman-aria/get`
`${API_BASE_URL}/sanitary/waterman-aura/get`
`${API_BASE_URL}/sanitary/waterman-dell/get`
`${API_BASE_URL}/sanitary/waterman-deluxe/get`
`${API_BASE_URL}/sanitary/waterman-eco/get`
`${API_BASE_URL}/sanitary/waterman-evoque/get`
`${API_BASE_URL}/sanitary/waterman-hand-showers/get`
`${API_BASE_URL}/sanitary/waterman-health-faucet-abs/get`
`${API_BASE_URL}/sanitary/waterman-health-faucets-brass/get`
`${API_BASE_URL}/sanitary/waterman-ikon/get`
`${API_BASE_URL}/sanitary/waterman-rain-showers/get`
`${API_BASE_URL}/sanitary/waterman-roman/get`
`${API_BASE_URL}/sanitary/waterman-shower-tubes/get`
`${API_BASE_URL}/sanitary/waterman-wall-showers-with-arm/get`
`${API_BASE_URL}/sanitary/waterman-wall-showers-without-arm/get`
`${API_BASE_URL}/sanitary/water-tec-allied/get`
`${API_BASE_URL}/sanitary/water-tec-aqua/get`
`${API_BASE_URL}/sanitary/water-tec-aspire/get`
`${API_BASE_URL}/sanitary/water-tec-bathroom-accessories/get`
`${API_BASE_URL}/sanitary/water-tec-cistern/get`
`${API_BASE_URL}/sanitary/water-tec-concealed-cistern/get`
`${API_BASE_URL}/sanitary/water-tec-connection-tube/get`
`${API_BASE_URL}/sanitary/water-tec-ebony/get`
`${API_BASE_URL}/sanitary/water-tec-eco/get`
`${API_BASE_URL}/sanitary/water-tec-eva/get`
`${API_BASE_URL}/sanitary/water-tec-flora/get`
`${API_BASE_URL}/sanitary/water-tec-health-faucets/get`
`${API_BASE_URL}/sanitary/water-tec-quattro/get`
`${API_BASE_URL}/sanitary/water-tec-showers/get`
`${API_BASE_URL}/sanitary/water-tec-tops/get`
`${API_BASE_URL}/sanitary/water-tec-toilet-seat-covers/get`
`${API_BASE_URL}/sanitary/water-tec-t-series-alt/get`
`${API_BASE_URL}/sanitary/water-tec-t-series/get`
`${API_BASE_URL}/sanitary/water-tec-valves/get`
`${API_BASE_URL}/tools/abrasives/cutOffWheel/get`
`${API_BASE_URL}/tools/abrasives/diamondBlades/get`
`${API_BASE_URL}/tools/allen-keys/get`
`${API_BASE_URL}/tools/brush/get`
`${API_BASE_URL}/tools/carpenter-pincer/get`
`${API_BASE_URL}/tools/centre-punches/get`
`${API_BASE_URL}/tools/chisels/get`
`${API_BASE_URL}/tools/clamps/get`
`${API_BASE_URL}/tools/cutters/get`
`${API_BASE_URL}/tools/files/get`
`${API_BASE_URL}/tools/garden-tools/get`
`${API_BASE_URL}/tools/gear-pullers/get`
`${API_BASE_URL}/tools/glass-cutter/get`
`${API_BASE_URL}/tools/gluegun/get`
`${API_BASE_URL}/tools/grease-gun/get`
`${API_BASE_URL}/tools/hacksaw-blades/get`
`${API_BASE_URL}/tools/hammer/get`
`${API_BASE_URL}/tools/hammer-drlls/get`
`${API_BASE_URL}/tools/handtools/get`
`${API_BASE_URL}/tools/level/get`
`${API_BASE_URL}/tools/lubrications/get`
`${API_BASE_URL}/tools/measurement-scale/get`
`${API_BASE_URL}/tools/measuring-tape/get`
`${API_BASE_URL}/tools/multimeter/get`
`${API_BASE_URL}/tools/plier/get`
`${API_BASE_URL}/tools/polishing-accessories/get`
`${API_BASE_URL}/tools/powertools/drill/get`
`${API_BASE_URL}/tools/powertools/grinders/get`
`${API_BASE_URL}/tools/powertools/marble-cutter/get`
`${API_BASE_URL}/tools/saw/get`
`${API_BASE_URL}/tools/screw-driver/get`
`${API_BASE_URL}/tools/silicon-gun/get`
`${API_BASE_URL}/tools/socketset/get`
`${API_BASE_URL}/tools/spanners/get`
`${API_BASE_URL}/tools/spare-malets/get`
`${API_BASE_URL}/tools/tool-compartments/get`
`${API_BASE_URL}/tools/toolkitset/get`
`${API_BASE_URL}/tools/various-tool-bits/get`
`${API_BASE_URL}/tools/wood-chisel/get`
`${API_BASE_URL}/tools/wood-items/get`
`${API_BASE_URL}/tools/wrench/get`
`${API_BASE_URL}/uncategorized/get`
`${API_BASE_URL}/waterproofing/bathroom/get`
`${API_BASE_URL}/waterproofing/creacks-joints/get`
`${API_BASE_URL}/waterproofing/interiors/get`