const express = require('express');
const router = express.Router();
const multer = require('multer');

const adaptors = require('../controllers/electrical/adaptorsController');
const ceilingRoses = require('../controllers/electrical/ceilingRosesController');
const wiresAndCables = require('../controllers/electrical/wiresAndCablesController');
const waterHeater = require('../controllers/electrical/waterHeaterController');
const uniSwitch = require('../controllers/electrical/uniSwitchController');
const tVOutlets = require('../controllers/electrical/tVOutletsController');
const travelAdaptor = require('../controllers/electrical/travelAdaptorController');
const switchPlates = require('../controllers/electrical/switchPlatesController');
const switches = require('../controllers/electrical/switchesController');
const switchAndSocket = require('../controllers/electrical/switchAndSocketController');
const sockets = require('../controllers/electrical/socketsController');
const rotarySwitch = require('../controllers/electrical/rotarySwitchController');
const regulators = require('../controllers/electrical/regulatorsController');
const pvCClips = require('../controllers/electrical/pvCClipsController');
const powerStrips = require('../controllers/electrical/powerStripsController');
const plug = require('../controllers/electrical/plugController');
const pinTop = require('../controllers/electrical/pinTopController');
const others = require('../controllers/electrical/othersController');
const motorStarters = require('../controllers/electrical/motorStartersController');
const motors = require('../controllers/electrical/motorsController');
const modularSurfaceBox = require('../controllers/electrical/modularSurfaceBoxController');
const mCB = require('../controllers/electrical/mCBController');
const mainSwitch = require('../controllers/electrical/mainSwitchController');
const lights = require('../controllers/electrical/lightsController');
const kITKATFuses = require('../controllers/electrical/kITKATFusesController');
const jacks = require('../controllers/electrical/jacksController');
const isolators = require('../controllers/electrical/isolatorsController');
const insulationTapes = require('../controllers/electrical/insulationTapesController');
const indicator = require('../controllers/electrical/indicatorController');
const holders = require('../controllers/electrical/holdersController');
const fuseCarriers = require('../controllers/electrical/fuseCarriersController');
const flexibleWires = require('../controllers/electrical/flexibleWiresController');
const flexibleConduit = require('../controllers/electrical/flexibleConduitController');
const fan = require('../controllers/electrical/fanController');
const electricalFittings = require('../controllers/electrical/electricalFittingsController');
const eLCBsRCCBs = require('../controllers/electrical/eLCBsRCCBsController');
const earthingAccessories = require('../controllers/electrical/earthingAccessoriesController');
const dPswitch = require('../controllers/electrical/dPswitchController');
const doorBells = require('../controllers/electrical/doorBellsController');
const distributionBoards = require('../controllers/electrical/distributionBoardsController');
const dimmer = require('../controllers/electrical/dimmerController');

const storage = multer.memoryStorage();
const upload = multer({ storage });

function crudRoutes(resource, controller) {
  router.post(`/${resource}`, upload.array('photos', 5), controller[`create${capitalize(resource)}`]);
  router.get(`/${resource}`, controller[`getAll${capitalize(resource)}`]);
  router.get(`/${resource}/:id`, controller[`getOne${capitalize(resource)}`]);
  router.put(`/${resource}/:id`, upload.array('photos', 5), controller[`update${capitalize(resource)}`]);
  router.delete(`/${resource}/:id`, controller[`delete${capitalize(resource)}`]);
}
function capitalize(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

crudRoutes('adaptors', adaptors);
crudRoutes('ceilingRoses', ceilingRoses);
crudRoutes('wiresAndCables', wiresAndCables);
crudRoutes('waterHeater', waterHeater);
crudRoutes('uniSwitch', uniSwitch);
crudRoutes('tVOutlets', tVOutlets);
crudRoutes('travelAdaptor', travelAdaptor);
crudRoutes('switchPlates', switchPlates);
crudRoutes('switches', switches);
crudRoutes('switchAndSocket', switchAndSocket);
crudRoutes('sockets', sockets);
crudRoutes('rotarySwitch', rotarySwitch);
crudRoutes('regulators', regulators);
crudRoutes('pvCClips', pvCClips);
crudRoutes('powerStrips', powerStrips);
crudRoutes('plug', plug);
crudRoutes('pinTop', pinTop);
crudRoutes('others', others);
crudRoutes('motorStarters', motorStarters);
crudRoutes('motors', motors);
crudRoutes('modularSurfaceBox', modularSurfaceBox);
crudRoutes('mCB', mCB);
crudRoutes('mainSwitch', mainSwitch);
crudRoutes('lights', lights);
crudRoutes('kITKATFuses', kITKATFuses);
crudRoutes('jacks', jacks);
crudRoutes('isolators', isolators);
crudRoutes('insulationTapes', insulationTapes);
crudRoutes('indicator', indicator);
crudRoutes('holders', holders);
crudRoutes('fuseCarriers', fuseCarriers);
crudRoutes('flexibleWires', flexibleWires);
crudRoutes('flexibleConduit', flexibleConduit);
crudRoutes('fan', fan);
crudRoutes('electricalFittings', electricalFittings);
crudRoutes('eLCBsRCCBs', eLCBsRCCBs);
crudRoutes('earthingAccessories', earthingAccessories);
crudRoutes('dPswitch', dPswitch);
crudRoutes('doorBells', doorBells);
crudRoutes('distributionBoards', distributionBoards);
crudRoutes('dimmer', dimmer);

module.exports = router;
