const express = require('express');
const router = express.Router();

const adaptors = require('../controllers/electrical/adaptorsController');
const fans = require('../controllers/electrical/fansController');
const lights = require('../controllers/electrical/lightsController');
const switches = require('../controllers/electrical/switchesController');
const sockets = require('../controllers/electrical/socketsController');
const plug = require('../controllers/electrical/plugController');
const waterHeater = require('../controllers/electrical/waterHeaterController');
const uniSwitch = require('../controllers/electrical/uniSwitchController');
const tVOutlets = require('../controllers/electrical/tVOutletsController');
const travelAdaptor = require('../controllers/electrical/travelAdaptorController');
const switchPlates = require('../controllers/electrical/switchPlatesController');
const switchAndSocket = require('../controllers/electrical/switchAndSocketController');
const rotarySwitch = require('../controllers/electrical/rotarySwitchController');
const regulators = require('../controllers/electrical/regulatorsController');
const pvCClips = require('../controllers/electrical/pvCClipsController');
const powerStrips = require('../controllers/electrical/powerStripsController');
const pinTop = require('../controllers/electrical/pinTopController');
const others = require('../controllers/electrical/othersController');
const motorStarters = require('../controllers/electrical/motorStartersController');
const motors = require('../controllers/electrical/motorsController');
const modularSurfaceBox = require('../controllers/electrical/modularSurfaceBoxController');
const mCB = require('../controllers/electrical/mCBController');
const mainSwitch = require('../controllers/electrical/mainSwitchController');
const kITKATFuses = require('../controllers/electrical/kITKATFusesController');
const jacks = require('../controllers/electrical/jacksController');
const isolators = require('../controllers/electrical/isolatorsController');
const insulationTapes = require('../controllers/electrical/insulationTapesController');
const indicator = require('../controllers/electrical/indicatorController');
const holders = require('../controllers/electrical/holdersController');
const fuseCarriers = require('../controllers/electrical/fuseCarriersController');
const flexibleWires = require('../controllers/electrical/flexibleWiresController');
const flexibleConduit = require('../controllers/electrical/flexibleConduitController');
const electricalFittings = require('../controllers/electrical/electricalFittingsController');
const eLCBsRCCBs = require('../controllers/electrical/eLCBsRCCBsController');
const earthingAccessories = require('../controllers/electrical/earthingAccessoriesController');
const dPswitch = require('../controllers/electrical/dPswitchController');
const doorBells = require('../controllers/electrical/doorBellsController');
const distributionBoards = require('../controllers/electrical/distributionBoardsController');
const dimmer = require('../controllers/electrical/dimmerController');
const ceilingRoses = require('../controllers/electrical/ceilingRosesController');
const wiresAndCables = require('../controllers/electrical/wiresAndCablesController');
const waterHeaters = require('../controllers/electrical/waterHeatersController');

// Helper to register CRUD routes
function registerRoutes(path, ctrl, name) {
  router.post(`/${path}`, ctrl[`create${name}`]);
  router.get(`/${path}`, ctrl[`getAll${name}s`]);
  router.get(`/${path}/:id`, ctrl[`get${name}ById`]);
  router.put(`/${path}/:id`, ctrl[`update${name}`]);
  router.delete(`/${path}/:id`, ctrl[`delete${name}`]);
}

registerRoutes('adaptors', adaptors, 'Adaptor');
registerRoutes('fans', fans, 'Fan');
registerRoutes('lights', lights, 'Light');
registerRoutes('switches', switches, 'Switch');
registerRoutes('sockets', sockets, 'Socket');
registerRoutes('plug', plug, 'Plug');
registerRoutes('waterHeater', waterHeater, 'WaterHeater');
registerRoutes('uniSwitch', uniSwitch, 'UniSwitch');
registerRoutes('tVOutlets', tVOutlets, 'TVOutlet');
registerRoutes('travelAdaptor', travelAdaptor, 'TravelAdaptor');
registerRoutes('switchPlates', switchPlates, 'SwitchPlate');
registerRoutes('switchAndSocket', switchAndSocket, 'SwitchAndSocket');
registerRoutes('rotarySwitch', rotarySwitch, 'RotarySwitch');
registerRoutes('regulators', regulators, 'Regulator');
registerRoutes('pvCClips', pvCClips, 'PVCClip');
registerRoutes('powerStrips', powerStrips, 'PowerStrip');
registerRoutes('pinTop', pinTop, 'PinTop');
registerRoutes('others', others, 'Other');
registerRoutes('motorStarters', motorStarters, 'MotorStarter');
registerRoutes('motors', motors, 'Motor');
registerRoutes('modularSurfaceBox', modularSurfaceBox, 'ModularSurfaceBox');
registerRoutes('mCB', mCB, 'MCB');
registerRoutes('mainSwitch', mainSwitch, 'MainSwitch');
registerRoutes('kITKATFuses', kITKATFuses, 'KITKATFuse');
registerRoutes('jacks', jacks, 'Jack');
registerRoutes('isolators', isolators, 'Isolator');
registerRoutes('insulationTapes', insulationTapes, 'InsulationTape');
registerRoutes('indicator', indicator, 'Indicator');
registerRoutes('holders', holders, 'Holder');
registerRoutes('fuseCarriers', fuseCarriers, 'FuseCarrier');
registerRoutes('flexibleWires', flexibleWires, 'FlexibleWire');
registerRoutes('flexibleConduit', flexibleConduit, 'FlexibleConduit');
registerRoutes('electricalFittings', electricalFittings, 'ElectricalFitting');
registerRoutes('eLCBsRCCBs', eLCBsRCCBs, 'ELCBsRCCB');
registerRoutes('earthingAccessories', earthingAccessories, 'EarthingAccessory');
registerRoutes('dPswitch', dPswitch, 'DPswitch');
registerRoutes('doorBells', doorBells, 'DoorBell');
registerRoutes('distributionBoards', distributionBoards, 'DistributionBoard');
registerRoutes('dimmer', dimmer, 'Dimmer');
registerRoutes('ceilingRoses', ceilingRoses, 'CeilingRoses');
registerRoutes('wiresAndCables', wiresAndCables, 'WiresAndCables');
registerRoutes('waterHeaters', waterHeaters, 'WaterHeater');

module.exports = router;
