// AUTO-RENAMED FUNCTIONS TO MATCH FILE NAME. DO NOT EDIT MANUALLY.
// AUTO-GENERATED. DO NOT EDIT MANUALLY.

const express = require('express');
const multer = require('multer');
const storage = multer.memoryStorage();
const upload = multer({ storage });
const router = express.Router();
const cutOffWheelController = require('../controllers/tools/abrasives/cutOffWheelController.js');
const diamondBladesController = require('../controllers/tools/abrasives/diamondBladesController.js');
const abrasivesController = require('../controllers/tools/abrasivesController.js');
const allenKeysController = require('../controllers/tools/allenKeysController.js');
const brushController = require('../controllers/tools/brushController.js');
const carpenterPincerController = require('../controllers/tools/carpenterPincerController.js');
const centrePunchesController = require('../controllers/tools/centrePunchesController.js');
const chiselsController = require('../controllers/tools/chiselsController.js');
const clampsController = require('../controllers/tools/clampsController.js');
const crowbarController = require('../controllers/tools/crowbarController.js');
const cuttersController = require('../controllers/tools/cuttersController.js');
const filesController = require('../controllers/tools/filesController.js');
const gardenToolsController = require('../controllers/tools/gardenToolsController.js');
const gearPullersController = require('../controllers/tools/gearPullersController.js');
const glassCutterController = require('../controllers/tools/glassCutterController.js');
const gluegunController = require('../controllers/tools/gluegunController.js');
const greaseGunController = require('../controllers/tools/greaseGunController.js');
const hacksawBladesController = require('../controllers/tools/hacksawBladesController.js');
const hammerController = require('../controllers/tools/hammerController.js');
const hammerDrillsController = require('../controllers/tools/hammerDrillsController.js');
const handtoolsController = require('../controllers/tools/handtoolsController.js');
const levelController = require('../controllers/tools/levelController.js');
const lubricationsController = require('../controllers/tools/lubricationsController.js');
const measurementScaleController = require('../controllers/tools/measurementScaleController.js');
const measuringTapeController = require('../controllers/tools/measuringTapeController.js');
const multimeterController = require('../controllers/tools/multimeterController.js');
const plierController = require('../controllers/tools/plierController.js');
const polishingAccessoriesController = require('../controllers/tools/polishingAccessoriesController.js');
const drillController = require('../controllers/tools/powerTools/drillController.js');
const grindersController = require('../controllers/tools/powerTools/grindersController.js');
const marbleCutterController = require('../controllers/tools/powerTools/marbleCutterController.js');
const powertoolsController = require('../controllers/tools/powertoolsController.js');
const sawController = require('../controllers/tools/sawController.js');
const screwDriverController = require('../controllers/tools/screwDriverController.js');
const siliconGunController = require('../controllers/tools/siliconGunController.js');
const socketsetController = require('../controllers/tools/socketsetController.js');
const spannersController = require('../controllers/tools/spannersController.js');
const spareMaletsController = require('../controllers/tools/spareMaletsController.js');
const toolCompartmentsController = require('../controllers/tools/toolCompartmentsController.js');
const toolkitsetController = require('../controllers/tools/toolkitsetController.js');
const varioustoolbitsController = require('../controllers/tools/varioustoolbitsController.js');
const woodChiselController = require('../controllers/tools/woodChiselController.js');
const woodItemsController = require('../controllers/tools/woodItemsController.js');
const wrenchController = require('../controllers/tools/wrenchController.js');

router.post('/api/tools/abrasives/cutOffWheel', upload.array('photos', 5), cutOffWheelController.createWrench);
router.get('/api/tools/abrasives/cutOffWheel', cutOffWheelController.getAllWrench);
router.get('/api/tools/abrasives/cutOffWheel/:id', cutOffWheelController.getOneWrench);
router.put('/api/tools/abrasives/cutOffWheel/:id', upload.array('photos', 5), cutOffWheelController.updateWrench);
router.deleteWrench('/api/tools/abrasives/cutOffWheel/:id', cutOffWheelController.deleteWrench);
router.post('/api/tools/abrasives/diamondBlades', upload.array('photos', 5), diamondBladesController.createWrench);
router.get('/api/tools/abrasives/diamondBlades', diamondBladesController.getAllWrench);
router.get('/api/tools/abrasives/diamondBlades/:id', diamondBladesController.getOneWrench);
router.put('/api/tools/abrasives/diamondBlades/:id', upload.array('photos', 5), diamondBladesController.updateWrench);
router.deleteWrench('/api/tools/abrasives/diamondBlades/:id', diamondBladesController.deleteWrench);
router.post('/api/tools/abrasives', upload.array('photos', 5), abrasivesController.createWrench);
router.get('/api/tools/abrasives', abrasivesController.getAllWrench);
router.get('/api/tools/abrasives/:id', abrasivesController.getOneWrench);
router.put('/api/tools/abrasives/:id', upload.array('photos', 5), abrasivesController.updateWrench);
router.deleteWrench('/api/tools/abrasives/:id', abrasivesController.deleteWrench);
router.post('/api/tools/allenKeys', upload.array('photos', 5), allenKeysController.createWrench);
router.get('/api/tools/allenKeys', allenKeysController.getAllWrench);
router.get('/api/tools/allenKeys/:id', allenKeysController.getOneWrench);
router.put('/api/tools/allenKeys/:id', upload.array('photos', 5), allenKeysController.updateWrench);
router.deleteWrench('/api/tools/allenKeys/:id', allenKeysController.deleteWrench);
router.post('/api/tools/brush', upload.array('photos', 5), brushController.createWrench);
router.get('/api/tools/brush', brushController.getAllWrench);
router.get('/api/tools/brush/:id', brushController.getOneWrench);
router.put('/api/tools/brush/:id', upload.array('photos', 5), brushController.updateWrench);
router.deleteWrench('/api/tools/brush/:id', brushController.deleteWrench);
router.post('/api/tools/carpenterPincer', upload.array('photos', 5), carpenterPincerController.createWrench);
router.get('/api/tools/carpenterPincer', carpenterPincerController.getAllWrench);
router.get('/api/tools/carpenterPincer/:id', carpenterPincerController.getOneWrench);
router.put('/api/tools/carpenterPincer/:id', upload.array('photos', 5), carpenterPincerController.updateWrench);
router.deleteWrench('/api/tools/carpenterPincer/:id', carpenterPincerController.deleteWrench);
router.post('/api/tools/centrePunches', upload.array('photos', 5), centrePunchesController.createWrench);
router.get('/api/tools/centrePunches', centrePunchesController.getAllWrench);
router.get('/api/tools/centrePunches/:id', centrePunchesController.getOneWrench);
router.put('/api/tools/centrePunches/:id', upload.array('photos', 5), centrePunchesController.updateWrench);
router.deleteWrench('/api/tools/centrePunches/:id', centrePunchesController.deleteWrench);
router.post('/api/tools/chisels', upload.array('photos', 5), chiselsController.createWrench);
router.get('/api/tools/chisels', chiselsController.getAllWrench);
router.get('/api/tools/chisels/:id', chiselsController.getOneWrench);
router.put('/api/tools/chisels/:id', upload.array('photos', 5), chiselsController.updateWrench);
router.deleteWrench('/api/tools/chisels/:id', chiselsController.deleteWrench);
router.post('/api/tools/clamps', upload.array('photos', 5), clampsController.createWrench);
router.get('/api/tools/clamps', clampsController.getAllWrench);
router.get('/api/tools/clamps/:id', clampsController.getOneWrench);
router.put('/api/tools/clamps/:id', upload.array('photos', 5), clampsController.updateWrench);
router.deleteWrench('/api/tools/clamps/:id', clampsController.deleteWrench);
router.post('/api/tools/crowbar', upload.array('photos', 5), crowbarController.createWrench);
router.get('/api/tools/crowbar', crowbarController.getAllWrench);
router.get('/api/tools/crowbar/:id', crowbarController.getOneWrench);
router.put('/api/tools/crowbar/:id', upload.array('photos', 5), crowbarController.updateWrench);
router.deleteWrench('/api/tools/crowbar/:id', crowbarController.deleteWrench);
router.post('/api/tools/cutters', upload.array('photos', 5), cuttersController.createWrench);
router.get('/api/tools/cutters', cuttersController.getAllWrench);
router.get('/api/tools/cutters/:id', cuttersController.getOneWrench);
router.put('/api/tools/cutters/:id', upload.array('photos', 5), cuttersController.updateWrench);
router.deleteWrench('/api/tools/cutters/:id', cuttersController.deleteWrench);
router.post('/api/tools/files', upload.array('photos', 5), filesController.createWrench);
router.get('/api/tools/files', filesController.getAllWrench);
router.get('/api/tools/files/:id', filesController.getOneWrench);
router.put('/api/tools/files/:id', upload.array('photos', 5), filesController.updateWrench);
router.deleteWrench('/api/tools/files/:id', filesController.deleteWrench);
router.post('/api/tools/gardenTools', upload.array('photos', 5), gardenToolsController.createWrench);
router.get('/api/tools/gardenTools', gardenToolsController.getAllWrench);
router.get('/api/tools/gardenTools/:id', gardenToolsController.getOneWrench);
router.put('/api/tools/gardenTools/:id', upload.array('photos', 5), gardenToolsController.updateWrench);
router.deleteWrench('/api/tools/gardenTools/:id', gardenToolsController.deleteWrench);
router.post('/api/tools/gearPullers', upload.array('photos', 5), gearPullersController.createWrench);
router.get('/api/tools/gearPullers', gearPullersController.getAllWrench);
router.get('/api/tools/gearPullers/:id', gearPullersController.getOneWrench);
router.put('/api/tools/gearPullers/:id', upload.array('photos', 5), gearPullersController.updateWrench);
router.deleteWrench('/api/tools/gearPullers/:id', gearPullersController.deleteWrench);
router.post('/api/tools/glassCutter', upload.array('photos', 5), glassCutterController.createWrench);
router.get('/api/tools/glassCutter', glassCutterController.getAllWrench);
router.get('/api/tools/glassCutter/:id', glassCutterController.getOneWrench);
router.put('/api/tools/glassCutter/:id', upload.array('photos', 5), glassCutterController.updateWrench);
router.deleteWrench('/api/tools/glassCutter/:id', glassCutterController.deleteWrench);
router.post('/api/tools/gluegun', upload.array('photos', 5), gluegunController.createWrench);
router.get('/api/tools/gluegun', gluegunController.getAllWrench);
router.get('/api/tools/gluegun/:id', gluegunController.getOneWrench);
router.put('/api/tools/gluegun/:id', upload.array('photos', 5), gluegunController.updateWrench);
router.deleteWrench('/api/tools/gluegun/:id', gluegunController.deleteWrench);
router.post('/api/tools/greaseGun', upload.array('photos', 5), greaseGunController.createWrench);
router.get('/api/tools/greaseGun', greaseGunController.getAllWrench);
router.get('/api/tools/greaseGun/:id', greaseGunController.getOneWrench);
router.put('/api/tools/greaseGun/:id', upload.array('photos', 5), greaseGunController.updateWrench);
router.deleteWrench('/api/tools/greaseGun/:id', greaseGunController.deleteWrench);
router.post('/api/tools/hacksawBlades', upload.array('photos', 5), hacksawBladesController.createWrench);
router.get('/api/tools/hacksawBlades', hacksawBladesController.getAllWrench);
router.get('/api/tools/hacksawBlades/:id', hacksawBladesController.getOneWrench);
router.put('/api/tools/hacksawBlades/:id', upload.array('photos', 5), hacksawBladesController.updateWrench);
router.deleteWrench('/api/tools/hacksawBlades/:id', hacksawBladesController.deleteWrench);
router.post('/api/tools/hammer', upload.array('photos', 5), hammerController.createWrench);
router.get('/api/tools/hammer', hammerController.getAllWrench);
router.get('/api/tools/hammer/:id', hammerController.getOneWrench);
router.put('/api/tools/hammer/:id', upload.array('photos', 5), hammerController.updateWrench);
router.deleteWrench('/api/tools/hammer/:id', hammerController.deleteWrench);
router.post('/api/tools/hammerDrills', upload.array('photos', 5), hammerDrillsController.createWrench);
router.get('/api/tools/hammerDrills', hammerDrillsController.getAllWrench);
router.get('/api/tools/hammerDrills/:id', hammerDrillsController.getOneWrench);
router.put('/api/tools/hammerDrills/:id', upload.array('photos', 5), hammerDrillsController.updateWrench);
router.deleteWrench('/api/tools/hammerDrills/:id', hammerDrillsController.deleteWrench);
router.post('/api/tools/handtools', upload.array('photos', 5), handtoolsController.createWrench);
router.get('/api/tools/handtools', handtoolsController.getAllWrench);
router.get('/api/tools/handtools/:id', handtoolsController.getOneWrench);
router.put('/api/tools/handtools/:id', upload.array('photos', 5), handtoolsController.updateWrench);
router.deleteWrench('/api/tools/handtools/:id', handtoolsController.deleteWrench);
router.post('/api/tools/level', upload.array('photos', 5), levelController.createWrench);
router.get('/api/tools/level', levelController.getAllWrench);
router.get('/api/tools/level/:id', levelController.getOneWrench);
router.put('/api/tools/level/:id', upload.array('photos', 5), levelController.updateWrench);
router.deleteWrench('/api/tools/level/:id', levelController.deleteWrench);
router.post('/api/tools/lubrications', upload.array('photos', 5), lubricationsController.createWrench);
router.get('/api/tools/lubrications', lubricationsController.getAllWrench);
router.get('/api/tools/lubrications/:id', lubricationsController.getOneWrench);
router.put('/api/tools/lubrications/:id', upload.array('photos', 5), lubricationsController.updateWrench);
router.deleteWrench('/api/tools/lubrications/:id', lubricationsController.deleteWrench);
router.post('/api/tools/measurementScale', upload.array('photos', 5), measurementScaleController.createWrench);
router.get('/api/tools/measurementScale', measurementScaleController.getAllWrench);
router.get('/api/tools/measurementScale/:id', measurementScaleController.getOneWrench);
router.put('/api/tools/measurementScale/:id', upload.array('photos', 5), measurementScaleController.updateWrench);
router.deleteWrench('/api/tools/measurementScale/:id', measurementScaleController.deleteWrench);
router.post('/api/tools/measuringTape', upload.array('photos', 5), measuringTapeController.createWrench);
router.get('/api/tools/measuringTape', measuringTapeController.getAllWrench);
router.get('/api/tools/measuringTape/:id', measuringTapeController.getOneWrench);
router.put('/api/tools/measuringTape/:id', upload.array('photos', 5), measuringTapeController.updateWrench);
router.deleteWrench('/api/tools/measuringTape/:id', measuringTapeController.deleteWrench);
router.post('/api/tools/multimeter', upload.array('photos', 5), multimeterController.createWrench);
router.get('/api/tools/multimeter', multimeterController.getAllWrench);
router.get('/api/tools/multimeter/:id', multimeterController.getOneWrench);
router.put('/api/tools/multimeter/:id', upload.array('photos', 5), multimeterController.updateWrench);
router.deleteWrench('/api/tools/multimeter/:id', multimeterController.deleteWrench);
router.post('/api/tools/plier', upload.array('photos', 5), plierController.createWrench);
router.get('/api/tools/plier', plierController.getAllWrench);
router.get('/api/tools/plier/:id', plierController.getOneWrench);
router.put('/api/tools/plier/:id', upload.array('photos', 5), plierController.updateWrench);
router.deleteWrench('/api/tools/plier/:id', plierController.deleteWrench);
router.post('/api/tools/polishingAccessories', upload.array('photos', 5), polishingAccessoriesController.createWrench);
router.get('/api/tools/polishingAccessories', polishingAccessoriesController.getAllWrench);
router.get('/api/tools/polishingAccessories/:id', polishingAccessoriesController.getOneWrench);
router.put('/api/tools/polishingAccessories/:id', upload.array('photos', 5), polishingAccessoriesController.updateWrench);
router.deleteWrench('/api/tools/polishingAccessories/:id', polishingAccessoriesController.deleteWrench);
router.post('/api/tools/powerTools/drill', upload.array('photos', 5), drillController.createWrench);
router.get('/api/tools/powerTools/drill', drillController.getAllWrench);
router.get('/api/tools/powerTools/drill/:id', drillController.getOneWrench);
router.put('/api/tools/powerTools/drill/:id', upload.array('photos', 5), drillController.updateWrench);
router.deleteWrench('/api/tools/powerTools/drill/:id', drillController.deleteWrench);
router.post('/api/tools/powerTools/grinders', upload.array('photos', 5), grindersController.createWrench);
router.get('/api/tools/powerTools/grinders', grindersController.getAllWrench);
router.get('/api/tools/powerTools/grinders/:id', grindersController.getOneWrench);
router.put('/api/tools/powerTools/grinders/:id', upload.array('photos', 5), grindersController.updateWrench);
router.deleteWrench('/api/tools/powerTools/grinders/:id', grindersController.deleteWrench);
router.post('/api/tools/powerTools/marbleCutter', upload.array('photos', 5), marbleCutterController.createWrench);
router.get('/api/tools/powerTools/marbleCutter', marbleCutterController.getAllWrench);
router.get('/api/tools/powerTools/marbleCutter/:id', marbleCutterController.getOneWrench);
router.put('/api/tools/powerTools/marbleCutter/:id', upload.array('photos', 5), marbleCutterController.updateWrench);
router.deleteWrench('/api/tools/powerTools/marbleCutter/:id', marbleCutterController.deleteWrench);
router.post('/api/tools/powertools', upload.array('photos', 5), powertoolsController.createWrench);
router.get('/api/tools/powertools', powertoolsController.getAllWrench);
router.get('/api/tools/powertools/:id', powertoolsController.getOneWrench);
router.put('/api/tools/powertools/:id', upload.array('photos', 5), powertoolsController.updateWrench);
router.deleteWrench('/api/tools/powertools/:id', powertoolsController.deleteWrench);
router.post('/api/tools/saw', upload.array('photos', 5), sawController.createWrench);
router.get('/api/tools/saw', sawController.getAllWrench);
router.get('/api/tools/saw/:id', sawController.getOneWrench);
router.put('/api/tools/saw/:id', upload.array('photos', 5), sawController.updateWrench);
router.deleteWrench('/api/tools/saw/:id', sawController.deleteWrench);
router.post('/api/tools/screwDriver', upload.array('photos', 5), screwDriverController.createWrench);
router.get('/api/tools/screwDriver', screwDriverController.getAllWrench);
router.get('/api/tools/screwDriver/:id', screwDriverController.getOneWrench);
router.put('/api/tools/screwDriver/:id', upload.array('photos', 5), screwDriverController.updateWrench);
router.deleteWrench('/api/tools/screwDriver/:id', screwDriverController.deleteWrench);
router.post('/api/tools/siliconGun', upload.array('photos', 5), siliconGunController.createWrench);
router.get('/api/tools/siliconGun', siliconGunController.getAllWrench);
router.get('/api/tools/siliconGun/:id', siliconGunController.getOneWrench);
router.put('/api/tools/siliconGun/:id', upload.array('photos', 5), siliconGunController.updateWrench);
router.deleteWrench('/api/tools/siliconGun/:id', siliconGunController.deleteWrench);
router.post('/api/tools/socketset', upload.array('photos', 5), socketsetController.createWrench);
router.get('/api/tools/socketset', socketsetController.getAllWrench);
router.get('/api/tools/socketset/:id', socketsetController.getOneWrench);
router.put('/api/tools/socketset/:id', upload.array('photos', 5), socketsetController.updateWrench);
router.deleteWrench('/api/tools/socketset/:id', socketsetController.deleteWrench);
router.post('/api/tools/spanners', upload.array('photos', 5), spannersController.createWrench);
router.get('/api/tools/spanners', spannersController.getAllWrench);
router.get('/api/tools/spanners/:id', spannersController.getOneWrench);
router.put('/api/tools/spanners/:id', upload.array('photos', 5), spannersController.updateWrench);
router.deleteWrench('/api/tools/spanners/:id', spannersController.deleteWrench);
router.post('/api/tools/spareMalets', upload.array('photos', 5), spareMaletsController.createWrench);
router.get('/api/tools/spareMalets', spareMaletsController.getAllWrench);
router.get('/api/tools/spareMalets/:id', spareMaletsController.getOneWrench);
router.put('/api/tools/spareMalets/:id', upload.array('photos', 5), spareMaletsController.updateWrench);
router.deleteWrench('/api/tools/spareMalets/:id', spareMaletsController.deleteWrench);
router.post('/api/tools/toolCompartments', upload.array('photos', 5), toolCompartmentsController.createWrench);
router.get('/api/tools/toolCompartments', toolCompartmentsController.getAllWrench);
router.get('/api/tools/toolCompartments/:id', toolCompartmentsController.getOneWrench);
router.put('/api/tools/toolCompartments/:id', upload.array('photos', 5), toolCompartmentsController.updateWrench);
router.deleteWrench('/api/tools/toolCompartments/:id', toolCompartmentsController.deleteWrench);
router.post('/api/tools/toolkitset', upload.array('photos', 5), toolkitsetController.createWrench);
router.get('/api/tools/toolkitset', toolkitsetController.getAllWrench);
router.get('/api/tools/toolkitset/:id', toolkitsetController.getOneWrench);
router.put('/api/tools/toolkitset/:id', upload.array('photos', 5), toolkitsetController.updateWrench);
router.deleteWrench('/api/tools/toolkitset/:id', toolkitsetController.deleteWrench);
router.post('/api/tools/varioustoolbits', upload.array('photos', 5), varioustoolbitsController.createWrench);
router.get('/api/tools/varioustoolbits', varioustoolbitsController.getAllWrench);
router.get('/api/tools/varioustoolbits/:id', varioustoolbitsController.getOneWrench);
router.put('/api/tools/varioustoolbits/:id', upload.array('photos', 5), varioustoolbitsController.updateWrench);
router.deleteWrench('/api/tools/varioustoolbits/:id', varioustoolbitsController.deleteWrench);
router.post('/api/tools/woodChisel', upload.array('photos', 5), woodChiselController.createWrench);
router.get('/api/tools/woodChisel', woodChiselController.getAllWrench);
router.get('/api/tools/woodChisel/:id', woodChiselController.getOneWrench);
router.put('/api/tools/woodChisel/:id', upload.array('photos', 5), woodChiselController.updateWrench);
router.deleteWrench('/api/tools/woodChisel/:id', woodChiselController.deleteWrench);
router.post('/api/tools/woodItems', upload.array('photos', 5), woodItemsController.createWrench);
router.get('/api/tools/woodItems', woodItemsController.getAllWrench);
router.get('/api/tools/woodItems/:id', woodItemsController.getOneWrench);
router.put('/api/tools/woodItems/:id', upload.array('photos', 5), woodItemsController.updateWrench);
router.deleteWrench('/api/tools/woodItems/:id', woodItemsController.deleteWrench);
router.post('/api/tools/wrench', upload.array('photos', 5), wrenchController.createWrench);
router.get('/api/tools/wrench', wrenchController.getAllWrench);
router.get('/api/tools/wrench/:id', wrenchController.getOneWrench);
router.put('/api/tools/wrench/:id', upload.array('photos', 5), wrenchController.updateWrench);
router.deleteWrench('/api/tools/wrench/:id', wrenchController.deleteWrench);

module.exports = router;
