import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UpdateWrapper from "@/components/UpdateWrapper";
import { AuthProvider } from '../components/AuthContext';
import ConditionalFooter from "@/components/ConditionalFooter";
import Header from '@/components/header';
import Navbar from '@/components/Navbar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hadware Sink",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <AuthProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased `}
          >
            <UpdateWrapper />
            <Header />
            <Navbar />
            <main className="">
              {children}
            </main>
            <ConditionalFooter />
          </body>
        </html>
      </AuthProvider>
  );
}


