import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import Header from "@/components/header";
// import Navbar from "@/components/Navbar";
import Footer from "@/components/footer";
// import { ClerkProvider } from "@clerk/nextjs";
import UpdateWrapper from "@/components/UpdateWrapper";
import { AuthProvider } from '../components/AuthContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ClerkProvider>
      <AuthProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased `}
          >
            {/* <Header /> */}
            {/* <Navbar /> */}
            <UpdateWrapper />
            {children}
            <Footer />
          </body>
        </html>
      </AuthProvider>
    // </ClerkProvider>
  );
}


