import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import dynamic from "next/dynamic";

const UpdateWrapper = dynamic(() => import("@/components/UpdateWrapper"), { ssr: false });
const ClientAuthProvider = dynamic(() => import("@/components/ClientAuthProvider"), { ssr: true });
const ClientCartProvider = dynamic(() => import("@/components/ClientCartProvider"), { ssr: true });
const ConditionalFooter = dynamic(() => import("@/components/ConditionalFooter"), { ssr: false });
const ConditionalHeader = dynamic(() => import("@/components/ConditionalHeader"), { ssr: false });
const ConditionalNavbar = dynamic(() => import("@/components/ConditionalNavbar"), { ssr: false });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Hadware Sink",
  description: "Generated by create next app",
};

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
export const revalidate = 0;

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ClientAuthProvider>
            <ClientCartProvider>
              <UpdateWrapper />
              <ConditionalHeader />
              <ConditionalNavbar />
              <main className="">
                {children}
              </main>
              <ConditionalFooter />
            </ClientCartProvider>
          </ClientAuthProvider>
        </body>
      </html>
  );
}


