`${API_BASE_URL}/adhesives/create`
`${API_BASE_URL}/brush/create`
`${API_BASE_URL}/cements/create`
`${API_BASE_URL}/cleaning/create`
`${API_BASE_URL}/dry/create`
`${API_BASE_URL}/electrical/adaptors/create`
`${API_BASE_URL}/electrical/ceilingRoses/create`
`${API_BASE_URL}/electrical/dimmer/create`
`${API_BASE_URL}/electrical/distributionBoards/create`
`${API_BASE_URL}/electrical/doorBells/create`
`${API_BASE_URL}/electrical/dPswitch/create`
`${API_BASE_URL}/electrical/earthingAccessories/create`
`${API_BASE_URL}/electrical/eLCBsRCCBs/create`
`${API_BASE_URL}/electrical/flexibleConduit/create`
`${API_BASE_URL}/electrical/flexibleWires/create`
`${API_BASE_URL}/electrical/fuseCarriers/create`
`${API_BASE_URL}/electrical/holders/create`
`${API_BASE_URL}/electrical/indicator/create`
`${API_BASE_URL}/electrical/insulationTapes/create`
`${API_BASE_URL}/electrical/isolators/create`
`${API_BASE_URL}/electrical/jacks/create`
`${API_BASE_URL}/electrical/kITKATFuses/create`
`${API_BASE_URL}/electrical/mainSwitch/create`
`${API_BASE_URL}/electrical/mCB/create`
`${API_BASE_URL}/electrical/modularSurfaceBox/create`
`${API_BASE_URL}/electrical/motors/create`
`${API_BASE_URL}/electrical/motorStarters/create`
`${API_BASE_URL}/electrical/others/create`
`${API_BASE_URL}/electrical/pinTop/create`
`${API_BASE_URL}/electrical/plug/create`
`${API_BASE_URL}/electrical/powerStrips/create`
`${API_BASE_URL}/electrical/pvCClips/create`
`${API_BASE_URL}/electrical/regulators/create`
`${API_BASE_URL}/electrical/rotarySwitch/create`
`${API_BASE_URL}/electrical/sockets/create`
`${API_BASE_URL}/electrical/switchAndSocket/create`
`${API_BASE_URL}/electrical/switches/create`
`${API_BASE_URL}/electrical/switchPlates/create`
`${API_BASE_URL}/electrical/travelAdaptor/create`
`${API_BASE_URL}/electrical/tVOutlets/create`
`${API_BASE_URL}/electrical/uniSwitch/create`
`${API_BASE_URL}/electrical/waterHeater/create`
`${API_BASE_URL}/electrical/wiresAndCables/create`
`${API_BASE_URL}/electrical/accessories/create`
`${API_BASE_URL}/electrical/circulardeepbox/create`
`${API_BASE_URL}/electrical/circularsurfacebox/create`
`${API_BASE_URL}/electrical/rigidtype/create`
`${API_BASE_URL}/electrical/cabinfans/create`
`${API_BASE_URL}/electrical/ceilingfans/create`
`${API_BASE_URL}/electrical/pedestalfans/create`
`${API_BASE_URL}/electrical/tablefans/create`
`${API_BASE_URL}/electrical/ventilationexhaustfans/create`
`${API_BASE_URL}/electrical/wallmountingfans/create`
`${API_BASE_URL}/electrical/ceilinglight/create`
`${API_BASE_URL}/electrical/cfl/create`
`${API_BASE_URL}/electrical/desklight/create`
`${API_BASE_URL}/electrical/focuslight/create`
`${API_BASE_URL}/electrical/gardenlight/create`
`${API_BASE_URL}/electrical/gatelight/create`
`${API_BASE_URL}/electrical/gls/create`
`${API_BASE_URL}/electrical/home/create`
`${API_BASE_URL}/electrical/lamps/create`
`${API_BASE_URL}/electrical/ledbatten/create`
`${API_BASE_URL}/electrical/ledbulbs/create`
`${API_BASE_URL}/electrical/leddownlightersspotlight/create`
`${API_BASE_URL}/electrical/ledluminaires/create`
`${API_BASE_URL}/electrical/ledpanellight/create`
`${API_BASE_URL}/electrical/ledspotlight/create`
`${API_BASE_URL}/electrical/ledstreetlight/create`
`${API_BASE_URL}/electrical/ledstrips/create`
`${API_BASE_URL}/electrical/ledsurfacelight/create`
`${API_BASE_URL}/electrical/lightelectronics/create`
`${API_BASE_URL}/electrical/mirrorlight/create`
`${API_BASE_URL}/electrical/reflections/create`
`${API_BASE_URL}/electrical/standardincandescent/create`
`${API_BASE_URL}/electrical/tbulb/create`
`${API_BASE_URL}/electrical/tubelight/create`
`${API_BASE_URL}/electrical/underwaterlights/create`
`${API_BASE_URL}/electrical/walllight/create`
`${API_BASE_URL}/fiber/create`
`${API_BASE_URL}/fitting/create`
`${API_BASE_URL}/hardware/create`
`${API_BASE_URL}/home/create`
`${API_BASE_URL}/homedecor/create`
`${API_BASE_URL}/locks/patch-fittings/create`
`${API_BASE_URL}/locks/mortise-lock-body/create`
`${API_BASE_URL}/locks/mortice-locks/create`
`${API_BASE_URL}/locks/door-accessories/concealed-hinges/create`
`${API_BASE_URL}/locks/door-accessories/door-eye/create`
`${API_BASE_URL}/locks/door-accessories/door-stopper/create`
`${API_BASE_URL}/locks/door-accessories/hinges/create`
`${API_BASE_URL}/locks/door-accessories/magnetic-door-stoppers/create`
`${API_BASE_URL}/locks/door-accessories/wooden-sliding-door-fittings/create`
`${API_BASE_URL}/locks/door-accessories/ball-bearing-door-hinges/create`
`${API_BASE_URL}/locks/door-controls/door-closer/create`
`${API_BASE_URL}/locks/door-controls/door-stopper/create`
`${API_BASE_URL}/locks/door-controls/hydraulic-door-closers/create`
`${API_BASE_URL}/locks/door-handles/door-kings/create`
`${API_BASE_URL}/locks/door-handles/door-pulls/create`
`${API_BASE_URL}/locks/door-locks/dimple-key/create`
`${API_BASE_URL}/locks/door-locks/diamant-padlocks/create`
`${API_BASE_URL}/locks/door-locks/dead-locks/create`
`${API_BASE_URL}/locks/door-locks/cylindrical-locks/create`
`${API_BASE_URL}/locks/door-locks/cupboard-locks/create`
`${API_BASE_URL}/locks/door-locks/centre-shutter-locks/create`
`${API_BASE_URL}/locks/door-locks/tri-bolt-locks/create`
`${API_BASE_URL}/locks/door-locks/smart-key/create`
`${API_BASE_URL}/locks/door-locks/side-lock'/create`
`${API_BASE_URL}/locks/door-locks/rim-dead-lock/create`
`${API_BASE_URL}/locks/door-locks/pull-handles-for-main-doors/create`
`${API_BASE_URL}/locks/door-locks/night-latch/create`
`${API_BASE_URL}/locks/door-locks/main-door-lock/create`
`${API_BASE_URL}/locks/door-locks/knob-locks/create`
`${API_BASE_URL}/locks/door-locks/jemmy-proof-door-lock/create`
`${API_BASE_URL}/locks/door-locks/drawer-lock/create`
`${API_BASE_URL}/locks/door-locks/disc-pad-locks/create`
`${API_BASE_URL}/locks/folding-brackets/thick-door-hinge/create`
`${API_BASE_URL}/locks/folding-brackets/soft-close-drawer-channel/create`
`${API_BASE_URL}/locks/folding-brackets/slip-on-hinge/create`
`${API_BASE_URL}/locks/folding-brackets/heavy-duty-drawer-slides/create`
`${API_BASE_URL}/locks/folding-brackets/folding-brackets/create`
`${API_BASE_URL}/locks/folding-brackets/drawer-channels/create`
`${API_BASE_URL}/locks/folding-brackets/clip-on-soft-hinge/create`
`${API_BASE_URL}/locks/folding-brackets/clip-on-soft-hinge-4-hole/create`
`${API_BASE_URL}/locks/folding-brackets/cabinet-hinge/create`
`${API_BASE_URL}/locks/folding-brackets/blind-corner-hinge/create`
`${API_BASE_URL}/locks/furniture-fittings/nuvo/create`
`${API_BASE_URL}/locks/furniture-fittings/multi-purpose-lock/create`
`${API_BASE_URL}/locks/furniture-fittings/furniture-fittings/create`
`${API_BASE_URL}/locks/furniture-fittings/drawer-locks/create`
`${API_BASE_URL}/locks/furniture-fittings/drawer-cupboard-lock/create`
`${API_BASE_URL}/locks/furniture-fittings/curvo/create`
`${API_BASE_URL}/locks/furniture-fittings/supernova/create`
`${API_BASE_URL}/locks/furniture-fittings/table-lock/create`
`${API_BASE_URL}/locks/glass-hardware/sliding-system/create`
`${API_BASE_URL}/locks/glass-hardware/shower-cubicle-hinge/create`
`${API_BASE_URL}/locks/glass-hardware/glass-hardware/create`
`${API_BASE_URL}/locks/glass-hardware/glass-door-pull-handle/create`
`${API_BASE_URL}/locks/glass-hardware/glass-door-lock/create`
`${API_BASE_URL}/locks/glass-hardware/glass-door-fitting/create`
`${API_BASE_URL}/locks/glass-hardware/floor-spring/create`
`${API_BASE_URL}/locks/glass-hardware/floor-spring-combo-set/create`
`${API_BASE_URL}/locks/lever-mortise-locks/lever-mortise-locks/create`
`${API_BASE_URL}/locks/lever-mortise-locks/exshi-security-cylinders/create`
`${API_BASE_URL}/locks/lever-mortise-locks/europrofile-mortise-pin-cylinder-with-master-key/create`
`${API_BASE_URL}/locks/lever-mortise-locks/europrofile-mortise-pin-cylinder/create`
`${API_BASE_URL}/locks/lever-mortise-locks/europrofile-mortise-lock-bodies/create`
`${API_BASE_URL}/locks/lever-mortise-locks/combipack-with-6-lever-mortise-lock/create`
`${API_BASE_URL}/locks/padlocks/ultra-shutter-locks/create`
`${API_BASE_URL}/locks/padlocks/square-type-padlock/create`
`${API_BASE_URL}/locks/padlocks/round-type-padlock/create`
`${API_BASE_URL}/locks/padlocks/premium-padlocks/create`
`${API_BASE_URL}/locks/padlocks/padlocks/create`
`${API_BASE_URL}/locks/padlocks/disc-padlocks/create`
`${API_BASE_URL}/locks/popular-mortise-series/victoria/create`
`${API_BASE_URL}/locks/popular-mortise-series/towy-low-height-design/create`
`${API_BASE_URL}/locks/popular-mortise-series/ssd-type-tube-lever/create`
`${API_BASE_URL}/locks/popular-mortise-series/pull-handles/create`
`${API_BASE_URL}/locks/popular-mortise-series/popular-mortise-series/create`
`${API_BASE_URL}/locks/popular-mortise-series/oliver/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh16/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh15-low-height-design/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh14/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh13/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh12/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh06/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh11/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh10/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh09/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh08/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh07/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh05/create`
`${API_BASE_URL}/locks/popular-mortise-series/neh04/create`
`${API_BASE_URL}/locks/popular-mortise-series/matiz/create`
`${API_BASE_URL}/locks/popular-mortise-series/main-door-set/create`
`${API_BASE_URL}/locks/popular-mortise-series/gloria/create`
`${API_BASE_URL}/locks/popular-mortise-series/cylindrical-locks/create`
`${API_BASE_URL}/locks/popular-mortise-series/corner-fetch-series/create`
`${API_BASE_URL}/locks/popular-mortise-series/combi-set/create`
`${API_BASE_URL}/locks/popular-mortise-series/classic-lock/create`
`${API_BASE_URL}/locks/popular-mortise-series/bm06/create`
`${API_BASE_URL}/locks/popular-mortise-series/bm04/create`
`${API_BASE_URL}/locks/popular-mortise-series/bm02/create`
`${API_BASE_URL}/locks/popular-mortise-series/bm01/create`
`${API_BASE_URL}/locks/premium-mortise-series/seh-series/create`
`${API_BASE_URL}/locks/premium-mortise-series/premium-mortise-series/create`
`${API_BASE_URL}/locks/premium-mortise-series/phoenix/create`
`${API_BASE_URL}/locks/premium-mortise-series/orbit/create`
`${API_BASE_URL}/locks/premium-mortise-series/mercury/create`
`${API_BASE_URL}/locks/premium-mortise-series/evva3ks-regalis-mortise/create`
`${API_BASE_URL}/locks/premium-mortise-series/europrofile-brass-handle-set-240mm/create`
`${API_BASE_URL}/locks/premium-mortise-series/combipack-with-240mm-euro-mortise-lock/create`
`${API_BASE_URL}/locks/premium-mortise-series/allure-rossette-series/create`
`${API_BASE_URL}/locks/rim-locks/ultra-xl-vertibolt/create`
`${API_BASE_URL}/locks/rim-locks/ultra-xl-twinbolt/create`
`${API_BASE_URL}/locks/rim-locks/ultra-xl-tribolt/create`
`${API_BASE_URL}/locks/rim-locks/ultra-xl-rim-deadbolt/create`
`${API_BASE_URL}/locks/rim-locks/ultra-vertibolt/create`
`${API_BASE_URL}/locks/rim-locks/ultra-tribolt/create`
`${API_BASE_URL}/locks/rim-locks/ultra-retrofit-adaptor/create`
`${API_BASE_URL}/locks/rim-locks/ultra-latchbolt-carton/create`
`${API_BASE_URL}/locks/rim-locks/rim-locks/create`
`${API_BASE_URL}/locks/rim-locks/pin-cylinder-rim-locks/create`
`${API_BASE_URL}/locks/rim-locks/pentabolt-aries/create`
`${API_BASE_URL}/locks/rim-locks/night-latch-7-lever/create`
`${API_BASE_URL}/locks/rim-locks/exs-astro/create`
`${API_BASE_URL}/locks/rim-locks/exs-altrix/create`
`${API_BASE_URL}/paint/acrylic-emulsion-paint/create`
`${API_BASE_URL}/paint/adhesive-thinner-adhesive/create`
`${API_BASE_URL}/paint/adhesive-thinner-thinner/create`
`${API_BASE_URL}/paint/aspa-paints/create`
`${API_BASE_URL}/paint/automative-paints-aspa-paints/create`
`${API_BASE_URL}/paint/brushes-rollers-paint-brushes/create`
`${API_BASE_URL}/paint/brushes-rollers-rollers/create`
`${API_BASE_URL}/paint/brushes-rollers-spray-paints/create`
`${API_BASE_URL}/paint/distemper-acrylic-distemper/create`
`${API_BASE_URL}/paint/distemper-synthetic-distemper/create`
`${API_BASE_URL}/paint/emulsion-exterior-emulsion/create`
`${API_BASE_URL}/paint/emulsion-interior-emulsion/create`
`${API_BASE_URL}/paint/emulsion-tile-guard/create`
`${API_BASE_URL}/paint/emulsion-wall-texture/create`
`${API_BASE_URL}/paint/enamel-gloss-enamel/create`
`${API_BASE_URL}/paint/enamel-satin-enamel/create`
`${API_BASE_URL}/paint/enamel-synthetic-enamel/create`
`${API_BASE_URL}/paint/exterior-paints/create`
`${API_BASE_URL}/paint/floor-paints/create`
`${API_BASE_URL}/paint/industrial-coatings/create`
`${API_BASE_URL}/paint/interior-paints/create`
`${API_BASE_URL}/paint/painting-accessories-painting-tools/create`
`${API_BASE_URL}/paint/painting-accessories-sandpaper-rolls/create`
`${API_BASE_URL}/paint/painting-accessories-stencils/create`
`${API_BASE_URL}/paint/painting-tools/create`
`${API_BASE_URL}/paint/primer-acrylic-primer/create`
`${API_BASE_URL}/paint/primer-cement-primer/create`
`${API_BASE_URL}/paint/primer-exterior-primer/create`
`${API_BASE_URL}/paint/primer-interior-primer/create`
`${API_BASE_URL}/paint/primer-metal-primer/create`
`${API_BASE_URL}/paint/primer-solvent-primer/create`
`${API_BASE_URL}/paint/primer-wood-primer/create`
`${API_BASE_URL}/paint/primer-and-wall-putty/create`
`${API_BASE_URL}/paint/sanitizer/create`
`${API_BASE_URL}/paint/spray-paints/create`
`${API_BASE_URL}/paint/stainers-thinners/create`
`${API_BASE_URL}/paint/stencils/create`
`${API_BASE_URL}/paint/tile-guard/create`
`${API_BASE_URL}/paint/top-brands-dulex-paints/create`
`${API_BASE_URL}/paint/top-brands-asian-paints/create`
`${API_BASE_URL}/paint/top-brands-neroloc-paints/create`
`${API_BASE_URL}/paint/top-brands-jk-wall-putty/create`
`${API_BASE_URL}/paint/wall-putty-acrylic-wall-putty/create`
`${API_BASE_URL}/paint/wall-putty-kpf-wall-putty/create`
`${API_BASE_URL}/paint/wall-putty-powder-wall-putty/create`
`${API_BASE_URL}/paint/wall-stickers-wallpapers/create`
`${API_BASE_URL}/paint/waterproofing-crack-fillers/create`
`${API_BASE_URL}/paint/waterproofing-waterproof-basecoat/create`
`${API_BASE_URL}/paint/wood-finishes-glass-coatings/create`
`${API_BASE_URL}/paint/wood-finishes-melamyne/create`
`${API_BASE_URL}/paint/wood-finishes-nc/create`
`${API_BASE_URL}/paint/wood-finishes-polish/create`
`${API_BASE_URL}/paint/wood-finishes-pu/create`
`${API_BASE_URL}/paint/wood-finishes-sealer/create`
`${API_BASE_URL}/paint/wood-finishes-varnish-black-board-paint/create`
`${API_BASE_URL}/paint/wood-finishes-wood-putty/create`
`${API_BASE_URL}/paint/wood-metal/create`
`${API_BASE_URL}/pipe/finolex-pipes/create`
`${API_BASE_URL}/pipe/ashirvad-pipes/create`
`${API_BASE_URL}/pipe/astral-pipes/create`
`${API_BASE_URL}/pipe/nepul-pipes/create`
`${API_BASE_URL}/pipe/birla-pipes/create`
`${API_BASE_URL}/pipe/prince-pipes/create`
`${API_BASE_URL}/pipe/prakash-pipes/create`
`${API_BASE_URL}/pipe/supreme-pipes/create`
`${API_BASE_URL}/pipe/tata-pipes/create`
`${API_BASE_URL}/pipe/tsa-pipes/create`
`${API_BASE_URL}/pvcmats/door/create`
`${API_BASE_URL}/pvcmats/floor/create`
`${API_BASE_URL}/roofer/metal/create`
`${API_BASE_URL}/roofer/shingles/create`
`${API_BASE_URL}/sanitary/acrylic-products/create`
`${API_BASE_URL}/sanitary/bathroom-accessories/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-altius/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-bathsense-essentials/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-bathsense-showers/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-colossus/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-invictus/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-maximus/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-spry/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-theta/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-essentials/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-pedestals/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-venus/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-washbasins/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-water-closet/create`
`${API_BASE_URL}/sanitary/closets/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-eurosmart-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-flowmore-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-new-super-glow-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-royale-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-treemo-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-xrossa-series/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-almond/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-arrow/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-bold/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-budget/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-concept/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-deluxe/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-eeco/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-expert/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-florence/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-glass-bowl-faucet/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-idea/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-jazz/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-ket/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-milano/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-nano/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-nexa/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-niagra/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-nice/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-omega/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-passion/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-royal/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-slimline/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-splash/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-square-f/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-square-s/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-super/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-tri/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-acrylic-accessories/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-almond/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-anglo/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-budget/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-dolphin/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-ecco/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-keti/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-qubix/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-square/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-supreme/create`
`${API_BASE_URL}/sanitary/corsa-flushing-cistern/create`
`${API_BASE_URL}/sanitary/corsa-kitchen-kitchen-faucets/create`
`${API_BASE_URL}/sanitary/corsa-kitchen-kitchen-sink/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-ball-valves/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-mini-angle-cock/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-mouth-operated/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-pressmatic-push-cock/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-sensor-taps/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-soap-dispenser/create`
`${API_BASE_URL}/sanitary/corsa-showers-health-faucet/create`
`${API_BASE_URL}/sanitary/corsa-shower-soverhead-shower/create`
`${API_BASE_URL}/sanitary/corsa-showers-rain-shower/create`
`${API_BASE_URL}/sanitary/corsa-showers-telephonic-shower/create`
`${API_BASE_URL}/sanitary/essess-accessories-series1-croma/create`
`${API_BASE_URL}/sanitary/essess-accessories-series2-swing/create`
`${API_BASE_URL}/sanitary/essess-accessories-series3-tarim/create`
`${API_BASE_URL}/sanitary/essess-accessories-series5-hotelier-series/create`
`${API_BASE_URL}/sanitary/essess-accessories-series6-cruzo/create`
`${API_BASE_URL}/sanitary/essess-accessories-series7-deon/create`
`${API_BASE_URL}/sanitary/essess-accessories-series8-series/create`
`${API_BASE_URL}/sanitary/essess-auto-close-taps/create`
`${API_BASE_URL}/sanitary/essess-celato/create`
`${API_BASE_URL}/sanitary/essess-croma/create`
`${API_BASE_URL}/sanitary/essess-cruzo/create`
`${API_BASE_URL}/sanitary/essess-deon/create`
`${API_BASE_URL}/sanitary/essess-series/create`
`${API_BASE_URL}/sanitary/essess-echo/create`
`${API_BASE_URL}/sanitary/essess-essentials/create`
`${API_BASE_URL}/sanitary/essess-hotelier-series/create`
`${API_BASE_URL}/sanitary/essess-s03/create`
`${API_BASE_URL}/sanitary/essess-lab-taps/create`
`${API_BASE_URL}/sanitary/essess-new-dune/create`
`${API_BASE_URL}/sanitary/essess-new-xess/create`
`${API_BASE_URL}/sanitary/essess-quadra/create`
`${API_BASE_URL}/sanitary/essess-sensors/create`
`${API_BASE_URL}/sanitary/essess-showers-hand-showers/create`
`${API_BASE_URL}/sanitary/essess-showers-overhead-showers/create`
`${API_BASE_URL}/sanitary/essess-showers-rainfall-showers/create`
`${API_BASE_URL}/sanitary/essess-showers-shower-arms/create`
`${API_BASE_URL}/sanitary/essess-tarim/create`
`${API_BASE_URL}/sanitary/essess-trand/create`
`${API_BASE_URL}/sanitary/faucets/create`
`${API_BASE_URL}/sanitary/hardware-bathroom-accessories/create`
`${API_BASE_URL}/sanitary/health-faucet/create`
`${API_BASE_URL}/sanitary/hindware-add-on/create`
`${API_BASE_URL}/sanitary/hindware-bath-tub/create`
`${API_BASE_URL}/sanitary/hindware-cisterns/create`
`${API_BASE_URL}/sanitary/hindware-faucets-angular-stop-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-bath-spout/create`
`${API_BASE_URL}/sanitary/hindware-faucets-bib-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-chbm/create`
`${API_BASE_URL}/sanitary/hindware-faucets-concealed-stop-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-csc-exp-kit/create`
`${API_BASE_URL}/sanitary/hindware-faucets-deusch-mixer/create`
`${API_BASE_URL}/sanitary/hindware-faucets-exposed-mixers/create`
`${API_BASE_URL}/sanitary/hindware-faucets-flush-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-medical-series/create`
`${API_BASE_URL}/sanitary/hindware-faucets-mixer-faucet/create`
`${API_BASE_URL}/sanitary/hindware-faucets-pillar-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-pillar-cock-tall/create`
`${API_BASE_URL}/sanitary/hindware-faucets-pillar-faucet/create`
`${API_BASE_URL}/sanitary/hindware-faucets-pressmatic/create`
`${API_BASE_URL}/sanitary/hindware-faucets-recessed/create`
`${API_BASE_URL}/sanitary/hindware-faucets-single-lever-divertor/create`
`${API_BASE_URL}/sanitary/hindware-faucets-sink-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-sink-mixer/create`
`${API_BASE_URL}/sanitary/hindware-faucets-slbm-faucet/create`
`${API_BASE_URL}/sanitary/hindware-faucets-slbm-faucet-tall/create`
`${API_BASE_URL}/sanitary/hindware-showers-rain-showers/create`
`${API_BASE_URL}/sanitary/hindware-wash-basins/create`
`${API_BASE_URL}/sanitary/hindware-water-closets/create`
`${API_BASE_URL}/sanitary/jaquar/create`
`${API_BASE_URL}/sanitary/kitchen-sinks/create`
`${API_BASE_URL}/sanitary/leo-bath-fittings-bathroom-accessories-bathroom-accessories/create`
`${API_BASE_URL}/sanitary/leo-bath-fittings-faucets-faucets/create`
`${API_BASE_URL}/sanitary/leo-bath-fittings-valve-valve/create`
`${API_BASE_URL}/sanitary/pamay-faucets-faucets/create`
`${API_BASE_URL}/sanitary/pamay-showers-showers/create`
`${API_BASE_URL}/sanitary/parryware-accessories-accessories/create`
`${API_BASE_URL}/sanitary/parryware-angle-valves-angle-valves/create`
`${API_BASE_URL}/sanitary/parryware-below-counter-basins-below-counter-basins/create`
`${API_BASE_URL}/sanitary/parryware-bowl-basins-bowl-basins/create`
`${API_BASE_URL}/sanitary/parryware-closets-closets/create`
`${API_BASE_URL}/sanitary/parryware-concealed-cistern-concealed-cistern/create`
`${API_BASE_URL}/sanitary/parryware-european-water-closet-european-water-closet/create`
`${API_BASE_URL}/sanitary/parryware-faucets-flush-cocks/create`
`${API_BASE_URL}/sanitary/parryware-faucets-flush-valve/create`
`${API_BASE_URL}/sanitary/parryware-faucets-health-faucets/create`
`${API_BASE_URL}/sanitary/parryware-faucets-kitchen-sinks/create`
`${API_BASE_URL}/sanitary/parryware-faucets-pedestals/create`
`${API_BASE_URL}/sanitary/parryware-polymer-cisterns-polymer-cisterns/create`
`${API_BASE_URL}/sanitary/parryware-push-plates-push-plates/create`
`${API_BASE_URL}/sanitary/parryware-seat-covers-seat-covers/create`
`${API_BASE_URL}/sanitary/parryware-semi-recessed-basins-semi-recessed-basins/create`
`${API_BASE_URL}/sanitary/parryware-shower-enclosures-shower-enclosures/create`
`${API_BASE_URL}/sanitary/parryware-shower-panels-shower-panels/create`
`${API_BASE_URL}/sanitary/parryware-showers-showers/create`
`${API_BASE_URL}/sanitary/parryware-utsav-range-utsav-range/create`
`${API_BASE_URL}/sanitary/parryware-wash-basins-wash-basins/create`
`${API_BASE_URL}/sanitary/parryware-waste-coupling-waste-coupling/create`
`${API_BASE_URL}/sanitary/parryware-water-heaters-water-heaters/create`
`${API_BASE_URL}/sanitary//pearl-precious-products-edge-edge/create`
`${API_BASE_URL}/sanitary/showers/create`
`${API_BASE_URL}/sanitary/taps/create`
`${API_BASE_URL}/sanitary/washbasins/create`
`${API_BASE_URL}/sanitary/waterman-accessories/create`
`${API_BASE_URL}/sanitary/waterman-aria/create`
`${API_BASE_URL}/sanitary/waterman-aura/create`
`${API_BASE_URL}/sanitary/waterman-dell/create`
`${API_BASE_URL}/sanitary/waterman-deluxe/create`
`${API_BASE_URL}/sanitary/waterman-eco/create`
`${API_BASE_URL}/sanitary/waterman-evoque/create`
`${API_BASE_URL}/sanitary/waterman-hand-showers/create`
`${API_BASE_URL}/sanitary/waterman-health-faucet-abs/create`
`${API_BASE_URL}/sanitary/waterman-health-faucets-brass/create`
`${API_BASE_URL}/sanitary/waterman-ikon/create`
`${API_BASE_URL}/sanitary/waterman-rain-showers/create`
`${API_BASE_URL}/sanitary/waterman-roman/create`
`${API_BASE_URL}/sanitary/waterman-shower-tubes/create`
`${API_BASE_URL}/sanitary/waterman-wall-showers-with-arm/create`
`${API_BASE_URL}/sanitary/waterman-wall-showers-without-arm/create`
`${API_BASE_URL}/sanitary/water-tec-allied/create`
`${API_BASE_URL}/sanitary/water-tec-aqua/create`
`${API_BASE_URL}/sanitary/water-tec-aspire/create`
`${API_BASE_URL}/sanitary/water-tec-bathroom-accessories/create`
`${API_BASE_URL}/sanitary/water-tec-cistern/create`
`${API_BASE_URL}/sanitary/water-tec-concealed-cistern/create`
`${API_BASE_URL}/sanitary/water-tec-connection-tube/create`
`${API_BASE_URL}/sanitary/water-tec-ebony/create`
`${API_BASE_URL}/sanitary/water-tec-eco/create`
`${API_BASE_URL}/sanitary/water-tec-eva/create`
`${API_BASE_URL}/sanitary/water-tec-flora/create`
`${API_BASE_URL}/sanitary/water-tec-health-faucets/create`
`${API_BASE_URL}/sanitary/water-tec-quattro/create`
`${API_BASE_URL}/sanitary/water-tec-showers/create`
`${API_BASE_URL}/sanitary/water-tec-tops/create`
`${API_BASE_URL}/sanitary/water-tec-toilet-seat-covers/create`
`${API_BASE_URL}/sanitary/water-tec-t-series-alt/create`
`${API_BASE_URL}/sanitary/water-tec-t-series/create`
`${API_BASE_URL}/sanitary/water-tec-valves/create`
`${API_BASE_URL}/tools/abrasives/cutOffWheel/create`
`${API_BASE_URL}/tools/abrasives/diamondBlades/create`
`${API_BASE_URL}/tools/allen-keys/create`
`${API_BASE_URL}/tools/brush/create`
`${API_BASE_URL}/tools/carpenter-pincer/create`
`${API_BASE_URL}/tools/centre-punches/create`
`${API_BASE_URL}/tools/chisels/create`
`${API_BASE_URL}/tools/clamps/create`
`${API_BASE_URL}/tools/cutters/create`
`${API_BASE_URL}/tools/files/create`
`${API_BASE_URL}/tools/garden-tools/create`
`${API_BASE_URL}/tools/gear-pullers/create`
`${API_BASE_URL}/tools/glass-cutter/create`
`${API_BASE_URL}/tools/gluegun/create`
`${API_BASE_URL}/tools/grease-gun/create`
`${API_BASE_URL}/tools/hacksaw-blades/create`
`${API_BASE_URL}/tools/hammer/create`
`${API_BASE_URL}/tools/hammer-drlls/create`
`${API_BASE_URL}/tools/handtools/create`
`${API_BASE_URL}/tools/level/create`
`${API_BASE_URL}/tools/lubrications/create`
`${API_BASE_URL}/tools/measurement-scale/create`
`${API_BASE_URL}/tools/measuring-tape/create`
`${API_BASE_URL}/tools/multimeter/create`
`${API_BASE_URL}/tools/plier/create`
`${API_BASE_URL}/tools/polishing-accessories/create`
`${API_BASE_URL}/tools/powertools/drill/create`
`${API_BASE_URL}/tools/powertools/grinders/create`
`${API_BASE_URL}/tools/powertools/marble-cutter/create`
`${API_BASE_URL}/tools/saw/create`
`${API_BASE_URL}/tools/screw-driver/create`
`${API_BASE_URL}/tools/silicon-gun/create`
`${API_BASE_URL}/tools/socketset/create`
`${API_BASE_URL}/tools/spanners/create`
`${API_BASE_URL}/tools/spare-malets/create`
`${API_BASE_URL}/tools/tool-compartments/create`
`${API_BASE_URL}/tools/toolkitset/create`
`${API_BASE_URL}/tools/various-tool-bits/create`
`${API_BASE_URL}/tools/wood-chisel/create`
`${API_BASE_URL}/tools/wood-items/create`
`${API_BASE_URL}/tools/wrench/create`
`${API_BASE_URL}/uncategorized/create`
`${API_BASE_URL}/waterproofing/bathroom/create`
`${API_BASE_URL}/waterproofing/creacks-joints/create`
`${API_BASE_URL}/waterproofing/interiors/create`