`${API_BASE_URL}/sanitary/acrylic-products/create`
`${API_BASE_URL}/sanitary/bathroom-accessories/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-altius/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-bathsense-essentials/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-bathsense-showers/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-colossus/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-invictus/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-maximus/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-spry/create`
`${API_BASE_URL}/sanitary/bathsense-pfittings-faucets-theta/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-essentials/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-pedestals/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-venus/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-washbasins/create`
`${API_BASE_URL}/sanitary/bathsense-sanitaryware-water-closet/create`
`${API_BASE_URL}/sanitary/closets/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-eurosmart-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-flowmore-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-new-super-glow-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-royale-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-treemo-series/create`
`${API_BASE_URL}/sanitary/coral-bath-fixtures-xrossa-series/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-almond/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-arrow/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-bold/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-budget/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-concept/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-deluxe/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-eeco/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-expert/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-florence/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-glass-bowl-faucet/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-idea/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-jazz/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-ket/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-milano/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-nano/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-nexa/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-niagra/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-nice/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-omega/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-passion/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-royal/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-slimline/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-splash/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-square-f/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-square-s/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-super/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-faucets-tri/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-acrylic-accessories/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-almond/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-anglo/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-budget/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-dolphin/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-ecco/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-keti/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-qubix/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-square/create`
`${API_BASE_URL}/sanitary/corsa-bathroom-accessories-supreme/create`
`${API_BASE_URL}/sanitary/corsa-flushing-cistern/create`
`${API_BASE_URL}/sanitary/corsa-kitchen-kitchen-faucets/create`
`${API_BASE_URL}/sanitary/corsa-kitchen-kitchen-sink/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-ball-valves/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-mini-angle-cock/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-mouth-operated/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-pressmatic-push-cock/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-sensor-taps/create`
`${API_BASE_URL}/sanitary/corsa-other-useful-items-soap-dispenser/create`
`${API_BASE_URL}/sanitary/corsa-showers-health-faucet/create`
`${API_BASE_URL}/sanitary/corsa-shower-soverhead-shower/create`
`${API_BASE_URL}/sanitary/corsa-showers-rain-shower/create`
`${API_BASE_URL}/sanitary/corsa-showers-telephonic-shower/create`
`${API_BASE_URL}/sanitary/essess-accessories-series1-croma/create`
`${API_BASE_URL}/sanitary/essess-accessories-series2-swing/create`
`${API_BASE_URL}/sanitary/essess-accessories-series3-tarim/create`
`${API_BASE_URL}/sanitary/essess-accessories-series5-hotelier-series/create`
`${API_BASE_URL}/sanitary/essess-accessories-series6-cruzo/create`
`${API_BASE_URL}/sanitary/essess-accessories-series7-deon/create`
`${API_BASE_URL}/sanitary/essess-accessories-series8-series/create`
`${API_BASE_URL}/sanitary/essess-auto-close-taps/create`
`${API_BASE_URL}/sanitary/essess-celato/create`
`${API_BASE_URL}/sanitary/essess-croma/create`
`${API_BASE_URL}/sanitary/essess-cruzo/create`
`${API_BASE_URL}/sanitary/essess-deon/create`
`${API_BASE_URL}/sanitary/essess-series/create`
`${API_BASE_URL}/sanitary/essess-echo/create`
`${API_BASE_URL}/sanitary/essess-essentials/create`
`${API_BASE_URL}/sanitary/essess-hotelier-series/create`
`${API_BASE_URL}/sanitary/essess-s03/create`
`${API_BASE_URL}/sanitary/essess-lab-taps/create`
`${API_BASE_URL}/sanitary/essess-new-dune/create`
`${API_BASE_URL}/sanitary/essess-new-xess/create`
`${API_BASE_URL}/sanitary/essess-quadra/create`
`${API_BASE_URL}/sanitary/essess-sensors/create`
`${API_BASE_URL}/sanitary/essess-showers-hand-showers/create`
`${API_BASE_URL}/sanitary/essess-showers-overhead-showers/create`
`${API_BASE_URL}/sanitary/essess-showers-rainfall-showers/create`
`${API_BASE_URL}/sanitary/essess-showers-shower-arms/create`
`${API_BASE_URL}/sanitary/essess-tarim/create`
`${API_BASE_URL}/sanitary/essess-trand/create`
`${API_BASE_URL}/sanitary/faucets/create`
`${API_BASE_URL}/sanitary/hardware-bathroom-accessories/create`
`${API_BASE_URL}/sanitary/health-faucet/create`
`${API_BASE_URL}/sanitary/hindware-add-on/create`
`${API_BASE_URL}/sanitary/hindware-bath-tub/create`
`${API_BASE_URL}/sanitary/hindware-cisterns/create`
`${API_BASE_URL}/sanitary/hindware-faucets-angular-stop-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-bath-spout/create`
`${API_BASE_URL}/sanitary/hindware-faucets-bib-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-chbm/create`
`${API_BASE_URL}/sanitary/hindware-faucets-concealed-stop-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-csc-exp-kit/create`
`${API_BASE_URL}/sanitary/hindware-faucets-deusch-mixer/create`
`${API_BASE_URL}/sanitary/hindware-faucets-exposed-mixers/create`
`${API_BASE_URL}/sanitary/hindware-faucets-flush-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-medical-series/create`
`${API_BASE_URL}/sanitary/hindware-faucets-mixer-faucet/create`
`${API_BASE_URL}/sanitary/hindware-faucets-pillar-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-pillar-cock-tall/create`
`${API_BASE_URL}/sanitary/hindware-faucets-pillar-faucet/create`
`${API_BASE_URL}/sanitary/hindware-faucets-pressmatic/create`
`${API_BASE_URL}/sanitary/hindware-faucets-recessed/create`
`${API_BASE_URL}/sanitary/hindware-faucets-single-lever-divertor/create`
`${API_BASE_URL}/sanitary/hindware-faucets-sink-cock/create`
`${API_BASE_URL}/sanitary/hindware-faucets-sink-mixer/create`
`${API_BASE_URL}/sanitary/hindware-faucets-slbm-faucet/create`
`${API_BASE_URL}/sanitary/hindware-faucets-slbm-faucet-tall/create`
`${API_BASE_URL}/sanitary/hindware-showers-rain-showers/create`
`${API_BASE_URL}/sanitary/hindware-wash-basins/create`
`${API_BASE_URL}/sanitary/hindware-water-closets/create`
`${API_BASE_URL}/sanitary/jaquar/create`
`${API_BASE_URL}/sanitary/kitchen-sinks/create`
`${API_BASE_URL}/sanitary/leo-bath-fittings-bathroom-accessories-bathroom-accessories/create`
`${API_BASE_URL}/sanitary/leo-bath-fittings-faucets/create`
`${API_BASE_URL}/sanitary/leo-bath-fittings-valve/create`
`${API_BASE_URL}/sanitary/pamay-faucets-faucets/create`
`${API_BASE_URL}/sanitary/pamay-showers-showers/create`
`${API_BASE_URL}/sanitary/parryware-accessories-accessories/create`
`${API_BASE_URL}/sanitary/parryware-angle-valves-angle-valves/create`
`${API_BASE_URL}/sanitary/parryware-below-counter-basins-below-counter-basins/create`
`${API_BASE_URL}/sanitary/parryware-bowl-basins-bowl-basins/create`
`${API_BASE_URL}/sanitary/parryware-closets-closets/create`
`${API_BASE_URL}/sanitary/parryware-concealed-cistern-concealed-cistern/create`
`${API_BASE_URL}/sanitary/parryware-european-water-closet-european-water-closet/create`
`${API_BASE_URL}/sanitary/parryware-faucets-flush-cocks/create`
`${API_BASE_URL}/sanitary/parryware-faucets-flush-valve/create`
`${API_BASE_URL}/sanitary/parryware-faucets-health-faucets/create`
`${API_BASE_URL}/sanitary/parryware-faucets-kitchen-sinks/create`
`${API_BASE_URL}/sanitary/parryware-faucets-pedestals/create`
`${API_BASE_URL}/sanitary/parryware-polymer-cisterns-polymer-cisterns/create`
`${API_BASE_URL}/sanitary/parryware-push-plates-push-plates/create`
`${API_BASE_URL}/sanitary/parryware-seat-covers-seat-covers/create`
`${API_BASE_URL}/sanitary/parryware-semi-recessed-basins-semi-recessed-basins/create`
`${API_BASE_URL}/sanitary/parryware-shower-enclosures-shower-enclosures/create`
`${API_BASE_URL}/sanitary/parryware-shower-panels-shower-panels/create`
`${API_BASE_URL}/sanitary/parryware-showers-showers/create`
`${API_BASE_URL}/sanitary/parryware-utsav-range-utsav-range/create`
`${API_BASE_URL}/sanitary/parryware-wash-basins-wash-basins/create`
`${API_BASE_URL}/sanitary/parryware-waste-coupling-waste-coupling/create`
`${API_BASE_URL}/sanitary/parryware-water-heaters-water-heaters/create`
`${API_BASE_URL}/sanitary/pearl-precious-products-edge-edge/create`
`${API_BASE_URL}/sanitary/showers/create`
`${API_BASE_URL}/sanitary/taps/create`
`${API_BASE_URL}/sanitary/washbasins/create`
`${API_BASE_URL}/sanitary/waterman-accessories/create`
`${API_BASE_URL}/sanitary/waterman-aria/create`
`${API_BASE_URL}/sanitary/waterman-aura/create`
`${API_BASE_URL}/sanitary/waterman-dell/create`
`${API_BASE_URL}/sanitary/waterman-deluxe/create`
`${API_BASE_URL}/sanitary/waterman-eco/create`
`${API_BASE_URL}/sanitary/waterman-evoque/create`
`${API_BASE_URL}/sanitary/waterman-hand-showers/create`
`${API_BASE_URL}/sanitary/waterman-health-faucet-abs/create`
`${API_BASE_URL}/sanitary/waterman-health-faucets-brass/create`
`${API_BASE_URL}/sanitary/waterman-ikon/create`
`${API_BASE_URL}/sanitary/waterman-rain-showers/create`
`${API_BASE_URL}/sanitary/waterman-roman/create`
`${API_BASE_URL}/sanitary/waterman-shower-tubes/create`
`${API_BASE_URL}/sanitary/waterman-wall-showers-with-arm/create`
`${API_BASE_URL}/sanitary/waterman-wall-showers-without-arm/create`
`${API_BASE_URL}/sanitary/water-tec-allied/create`
`${API_BASE_URL}/sanitary/water-tec-aqua/create`
`${API_BASE_URL}/sanitary/water-tec-aspire/create`
`${API_BASE_URL}/sanitary/water-tec-bathroom-accessories/create`
`${API_BASE_URL}/sanitary/water-tec-cistern/create`
`${API_BASE_URL}/sanitary/water-tec-concealed-cistern/create`
`${API_BASE_URL}/sanitary/water-tec-connection-tube/create`
`${API_BASE_URL}/sanitary/water-tec-ebony/create`
`${API_BASE_URL}/sanitary/water-tec-eco/create`
`${API_BASE_URL}/sanitary/water-tec-eva/create`
`${API_BASE_URL}/sanitary/water-tec-flora/create`
`${API_BASE_URL}/sanitary/water-tec-health-faucets/create`
`${API_BASE_URL}/sanitary/water-tec-quattro/create`
`${API_BASE_URL}/sanitary/water-tec-showers/create`
`${API_BASE_URL}/sanitary/water-tec-tops/create`
`${API_BASE_URL}/sanitary/water-tec-toilet-seat-covers/create`
`${API_BASE_URL}/sanitary/water-tec-t-series-alt/create`
`${API_BASE_URL}/sanitary/water-tec-t-series/create`
`${API_BASE_URL}/sanitary/water-tec-valves/create`